/* ==========================================================================
   OFFICIAL CAMBRIDGE YLE ENGLISH VOCABULARY DATABASE (1000+ WORDS)
   ========================================================================== */
const YLE_VOCABULARY = {
  starters: [
    { word: 'a lot', emoji: '📦', hint: '很多', mode: 'grammar', sentence: 'I like reading ___.', options: ['a lot', 'many', 'lots', 'much'], correct: 'a lot', translation: '我非常喜歡閱讀。' },
    { word: 'a lot of', emoji: 'Ⓐ', hint: '很多', mode: 'grammar', sentence: 'There are ___ children in the park.', options: ['a lot of', 'much', 'any', 'an'], correct: 'a lot of', translation: '公園裡有許多小孩。' },
    { word: 'about', emoji: 'Ⓐ', hint: '關於', mode: 'grammar', sentence: 'This book is ___ dinosaurs.', options: ['about', 'on', 'under', 'at'], correct: 'about', translation: '這本書是關於恐龍的。' },
    { word: 'add', emoji: '➕', hint: '添加', mode: 'spell' },
    { word: 'afternoon', emoji: 'Ⓐ', hint: '午安', mode: 'spell' },
    { word: 'again', emoji: '🔁', hint: '再次', mode: 'match' },
    { word: 'alien', emoji: '👽', hint: '外星人', mode: 'listening' },
    { word: 'alphabet', emoji: '🔤', hint: '字母', mode: 'listening' },
    { word: 'an', emoji: 'Ⓐ', hint: '一個', mode: 'grammar', sentence: 'I want ___ orange, please.', options: ['an', 'a', 'some', 'the'], correct: 'an', translation: '請給我一個橘子。' },
    { word: 'and', emoji: 'Ⓐ', hint: '和', mode: 'grammar', sentence: 'I like apples ___ bananas.', options: ['and', 'but', 'or', 'so'], correct: 'and', translation: '我喜歡蘋果和香蕉。' },
    { word: 'angry', emoji: '😠', hint: '生氣', mode: 'listening' },
    { word: 'animal', emoji: '🐾', hint: '動物', mode: 'match' },
    { word: 'answer', emoji: 'Ⓐ', hint: '回答', mode: 'spell' },
    { word: 'apple', emoji: '🍎', hint: '蘋果', mode: 'match' },
    { word: 'arm', emoji: '💪', hint: '手臂', mode: 'match' },
    { word: 'armchair', emoji: '🪑', hint: '扶手椅', mode: 'listening' },
    { word: 'at', emoji: 'Ⓐ', hint: '在', mode: 'grammar', sentence: 'The family is ___ home.', options: ['at', 'in', 'on', 'to'], correct: 'at', translation: '那家人在家。' },
    { word: 'baby', emoji: '👶', hint: '寶貝', mode: 'match' },
    { word: 'badminton', emoji: '🏸', hint: '羽毛球', mode: 'match' },
    { word: 'bag', emoji: '👜', hint: '包包', mode: 'match' },
    { word: 'ball', emoji: '⚽', hint: '球', mode: 'listening' },
    { word: 'balloon', emoji: '🎈', hint: '氣球', mode: 'listening' },
    { word: 'banana', emoji: '🍌', hint: '香蕉', mode: 'listening' },
    { word: 'baseball', emoji: '⚾', hint: '棒球', mode: 'match' },
    { word: 'baseball cap', emoji: '🧢', hint: '棒球帽', mode: 'match' },
    { word: 'bath', emoji: '🛀', hint: '洗澡', mode: 'listening' },
    { word: 'bathroom', emoji: '🛁', hint: '浴室', mode: 'match' },
    { word: 'be', emoji: 'Ⓑ', hint: '是', mode: 'spell' },
    { word: 'bean', emoji: 'Ⓑ', hint: '豆', mode: 'spell' },
    { word: 'bear', emoji: '🐻', hint: '熊', mode: 'match' },
    { word: 'beautiful', emoji: '✨', hint: '美麗的', mode: 'listening' },
    { word: 'bed', emoji: '🛏️', hint: '床', mode: 'listening' },
    { word: 'bedroom', emoji: '🛏', hint: '臥室', mode: 'match' },
    { word: 'bee', emoji: '🐝', hint: '蜜蜂', mode: 'match' },
    { word: 'behind', emoji: '⛅', hint: '後面', mode: 'grammar', sentence: 'The cat is hiding ___ the door.', options: ['behind', 'on', 'under', 'between'], correct: 'behind', translation: '貓躲在門後面。' },
    { word: 'big', emoji: '⛰️', hint: '大', mode: 'match' },
    { word: 'bike', emoji: '🚲', hint: '自行車', mode: 'listening' },
    { word: 'bird', emoji: '🐦', hint: '鳥', mode: 'listening' },
    { word: 'birthday', emoji: '🎂', hint: '生日', mode: 'listening' },
    { word: 'black', emoji: '⚫', hint: '黑色', mode: 'listening' },
    { word: 'blue', emoji: '🔵', hint: '藍色', mode: 'match' },
    { word: 'board', emoji: '📋', hint: '黑板/白板', mode: 'match' },
    { word: 'board game', emoji: 'Ⓑ', hint: '棋盤遊戲', mode: 'spell' },
    { word: 'boat', emoji: '⛵', hint: '船', mode: 'match' },
    { word: 'body', emoji: 'Ⓑ', hint: '身體', mode: 'spell' },
    { word: 'book', emoji: '📖', hint: '書', mode: 'listening' },
    { word: 'bookcase', emoji: 'Ⓑ', hint: '書櫃', mode: 'spell' },
    { word: 'boots', emoji: '👢', hint: '靴子', mode: 'listening' },
    { word: 'bounce', emoji: 'Ⓑ', hint: '彈跳', mode: 'spell' },
    { word: 'box', emoji: '📦', hint: '盒子', mode: 'listening' },
    { word: 'boy', emoji: '👦', hint: '男孩', mode: 'match' },
    { word: 'bread', emoji: '🍞', hint: '麵包', mode: 'match' },
    { word: 'breakfast', emoji: '🍳', hint: '早餐', mode: 'listening' },
    { word: 'brother', emoji: '👦', hint: '兄弟', mode: 'match' },
    { word: 'brown', emoji: '🟤', hint: '棕色', mode: 'match' },
    { word: 'burger', emoji: '🍔', hint: '漢堡', mode: 'listening' },
    { word: 'bus', emoji: '🚌', hint: '巴士', mode: 'match' },
    { word: 'but', emoji: 'Ⓑ', hint: '但是', mode: 'grammar', sentence: 'I like cake, ___ I don\'t like ice cream.', options: ['but', 'and', 'or', 'so'], correct: 'but', translation: '我喜歡蛋糕，但不喜歡冰淇淋。' },
    { word: 'cake', emoji: '🍰', hint: '蛋糕', mode: 'match' },
    { word: 'can', emoji: 'Ⓒ', hint: '可以', mode: 'spell' },
    { word: 'car', emoji: '🚗', hint: '汽車', mode: 'match' },
    { word: 'carrot', emoji: '🥕', hint: '紅蘿蔔', mode: 'listening' },
    { word: 'cat', emoji: '🐱', hint: '貓', mode: 'match' },
    { word: 'chair', emoji: '🪑', hint: '椅子', mode: 'spell' },
    { word: 'chicken', emoji: '🐔', hint: '雞', mode: 'listening' },
    { word: 'child', emoji: '🧒', hint: '孩子', mode: 'match' },
    { word: 'chips', emoji: '🍟', hint: '薯條', mode: 'listening' },
    { word: 'chocolate', emoji: '🍫', hint: '巧克力', mode: 'match' },
    { word: 'clap', emoji: '👏', hint: '拍手', mode: 'match' },
    { word: 'class', emoji: '🏫', hint: '班級', mode: 'match' },
    { word: 'classmate', emoji: '🧑', hint: '同學', mode: 'listening' },
    { word: 'classroom', emoji: '🏫', hint: '教室', mode: 'spell' },
    { word: 'clock', emoji: '⏰', hint: '時鐘', mode: 'match' },
    { word: 'close', emoji: 'Ⓒ', hint: '關閉', mode: 'spell' },
    { word: 'closed', emoji: 'Ⓒ', hint: '關閉', mode: 'spell' },
    { word: 'clothes', emoji: '👚', hint: '衣服', mode: 'match' },
    { word: 'coconut', emoji: '🥥', hint: '椰子', mode: 'listening' },
    { word: 'colour', emoji: 'Ⓒ', hint: '顏色', mode: 'spell' },
    { word: 'come', emoji: 'Ⓒ', hint: '來吧', mode: 'spell' },
    { word: 'complete', emoji: '✅', hint: '完成', mode: 'listening' },
    { word: 'computer', emoji: '💻', hint: '電腦', mode: 'listening' },
    { word: 'cool', emoji: '🆒', hint: '酷', mode: 'listening' },
    { word: 'correct', emoji: 'Ⓒ', hint: '正確', mode: 'spell' },
    { word: 'cousin', emoji: '🧑', hint: '表弟', mode: 'listening' },
    { word: 'cow', emoji: '🐮', hint: '牛', mode: 'listening' },
    { word: 'crayon', emoji: '🖍️', hint: '蠟筆', mode: 'match' },
    { word: 'crocodile', emoji: '🐊', hint: '鱷魚', mode: 'match' },
    { word: 'cupboard', emoji: 'Ⓒ', hint: '櫥櫃', mode: 'spell' },
    { word: 'dad', emoji: '👨', hint: '爸爸', mode: 'listening' },
    { word: 'day', emoji: 'Ⓓ', hint: '日', mode: 'spell' },
    { word: 'desk', emoji: 'Ⓓ', hint: '書桌', mode: 'spell' },
    { word: 'dining room', emoji: '🍽', hint: '餐廳', mode: 'match' },
    { word: 'dinner', emoji: '🍽️', hint: '晚餐', mode: 'match' },
    { word: 'do', emoji: 'Ⓓ', hint: '做', mode: 'spell' },
    { word: 'dog', emoji: '🐶', hint: '狗', mode: 'match' },
    { word: 'doll', emoji: 'Ⓓ', hint: '娃娃', mode: 'spell' },
    { word: 'donkey', emoji: '🫏', hint: '驢', mode: 'match' },
    { word: 'door', emoji: '🚪', hint: '門', mode: 'match' },
    { word: 'double', emoji: 'Ⓓ', hint: '雙', mode: 'spell' },
    { word: 'draw', emoji: 'Ⓓ', hint: '畫', mode: 'spell' },
    { word: 'drawing', emoji: 'Ⓓ', hint: '繪圖', mode: 'spell' },
    { word: 'dress', emoji: '👗', hint: '洋裝', mode: 'listening' },
    { word: 'drink', emoji: '🍸', hint: '喝', mode: 'match' },
    { word: 'drive', emoji: '🚗', hint: '開車', mode: 'match' },
    { word: 'duck', emoji: '🦆', hint: '鴨子', mode: 'listening' },
    { word: 'ear', emoji: '👂', hint: '耳朵', mode: 'match' },
    { word: 'eat', emoji: 'Ⓔ', hint: '吃', mode: 'spell' },
    { word: 'egg', emoji: '🥚', hint: '蛋', mode: 'listening' },
    { word: 'eight', emoji: '8️⃣', hint: '八', mode: 'listening' },
    { word: 'elephant', emoji: '🐘', hint: '大象', mode: 'listening' },
    { word: 'eleven', emoji: 'Ⓔ', hint: '十一', mode: 'spell' },
    { word: 'end', emoji: 'Ⓔ', hint: '結束', mode: 'spell' },
    { word: 'English', emoji: 'Ⓔ', hint: '英語', mode: 'spell' },
    { word: 'evening', emoji: 'Ⓔ', hint: '晚上', mode: 'spell' },
    { word: 'example', emoji: 'Ⓔ', hint: '例子', mode: 'spell' },
    { word: 'eye', emoji: '👁️', hint: '眼睛', mode: 'listening' },
    { word: 'face', emoji: '😀', hint: '臉', mode: 'listening' },
    { word: 'family', emoji: '👪', hint: '家庭', mode: 'match' },
    { word: 'fantastic', emoji: 'Ⓕ', hint: '太棒了', mode: 'spell' },
    { word: 'favourite', emoji: 'Ⓕ', hint: '最喜歡的', mode: 'spell' },
    { word: 'fifteen', emoji: 'Ⓕ', hint: '十五', mode: 'spell' },
    { word: 'find', emoji: 'Ⓕ', hint: '找到', mode: 'spell' },
    { word: 'fish', emoji: '🐟', hint: '魚', mode: 'match' },
    { word: 'fishing', emoji: '🎣', hint: '釣魚', mode: 'match' },
    { word: 'five', emoji: '5️⃣', hint: '五', mode: 'match' },
    { word: 'flat', emoji: '🏢', hint: '公寓', mode: 'listening' },
    { word: 'floor', emoji: 'Ⓕ', hint: '地板', mode: 'spell' },
    { word: 'flower', emoji: '🌸', hint: '花', mode: 'listening' },
    { word: 'fly', emoji: '✈️', hint: '飛翔（風箏/飛機）', mode: 'listening' },
    { word: 'food', emoji: '🍲', hint: '食物', mode: 'match' },
    { word: 'foot', emoji: '🦶', hint: '腳', mode: 'match' },
    { word: 'football', emoji: '⚽', hint: '足球', mode: 'listening' },
    { word: 'for', emoji: 'Ⓕ', hint: '為了（你）', mode: 'grammar', sentence: 'This gift is ___ you.', options: ['for', 'to', 'at', 'with'], correct: 'for', translation: '這個禮物是給你的。' },
    { word: 'four', emoji: '4️⃣', hint: '四', mode: 'match' },
    { word: 'fourteen', emoji: '1️⃣4️⃣', hint: '十四', mode: 'spell' },
    { word: 'friend', emoji: '🤝', hint: '朋友', mode: 'match' },
    { word: 'frog', emoji: '🐸', hint: '青蛙', mode: 'match' },
    { word: 'from', emoji: 'Ⓕ', hint: '來自', mode: 'grammar', sentence: 'This postcard is ___ my grandma.', options: ['from', 'to', 'at', 'for'], correct: 'from', translation: '這張明信片是我祖母寄來的。' },
    { word: 'fruit', emoji: '🍏', hint: '水果', mode: 'match' },
    { word: 'fun', emoji: 'Ⓕ', hint: '有趣', mode: 'spell' },
    { word: 'funny', emoji: '🤪', hint: '有趣的', mode: 'match' },
    { word: 'game', emoji: '👾', hint: '遊戲', mode: 'match' },
    { word: 'garden', emoji: '🏡', hint: '花園', mode: 'listening' },
    { word: 'get', emoji: 'Ⓖ', hint: '得到', mode: 'spell' },
    { word: 'giraffe', emoji: '🦒', hint: '長頸鹿', mode: 'match' },
    { word: 'girl', emoji: '👧', hint: '女孩', mode: 'match' },
    { word: 'give', emoji: 'Ⓖ', hint: '給予', mode: 'spell' },
    { word: 'glasses', emoji: '👓', hint: '眼鏡', mode: 'match' },
    { word: 'go', emoji: 'Ⓖ', hint: '去', mode: 'spell' },
    { word: 'go to bed', emoji: '🛌', hint: '上床睡覺', mode: 'match' },
    { word: 'go to sleep', emoji: '😴', hint: '入睡', mode: 'match' },
    { word: 'goat', emoji: '🐐', hint: '山羊', mode: 'listening' },
    { word: 'good', emoji: '👍', hint: '好', mode: 'listening' },
    { word: 'grandfather', emoji: '👴', hint: '祖父', mode: 'match' },
    { word: 'grandma', emoji: '👵', hint: '奶奶', mode: 'match' },
    { word: 'grandmother', emoji: '👵', hint: '祖母', mode: 'listening' },
    { word: 'grandpa', emoji: '👴', hint: '爺爺', mode: 'listening' },
    { word: 'grape', emoji: 'Ⓖ', hint: '葡萄', mode: 'spell' },
    { word: 'green', emoji: '🟢', hint: '綠色', mode: 'listening' },
    { word: 'grey', emoji: '⚪', hint: '灰色', mode: 'listening' },
    { word: 'guitar', emoji: '🎸', hint: '吉他', mode: 'match' },
    { word: 'hair', emoji: '🦰', hint: '頭髮', mode: 'match' },
    { word: 'hall', emoji: '🚪', hint: '大廳', mode: 'listening' },
    { word: 'hand', emoji: '✋', hint: '手', mode: 'listening' },
    { word: 'handbag', emoji: 'Ⓗ', hint: '手提包', mode: 'spell' },
    { word: 'happy', emoji: '😄', hint: '快樂', mode: 'match' },
    { word: 'hat', emoji: '🎩', hint: '帽子', mode: 'listening' },
    { word: 'have', emoji: 'Ⓗ', hint: '有', mode: 'spell' },
    { word: 'have got', emoji: 'Ⓗ', hint: '有', mode: 'spell' },
    { word: 'he', emoji: 'Ⓗ', hint: '他', mode: 'grammar', sentence: 'This is my dad. ___ is a doctor.', options: ['He', 'She', 'It', 'They'], correct: 'He', translation: '這是我爸爸。他是一位醫生。' },
    { word: 'head', emoji: '🤕', hint: '頭', mode: 'match' },
    { word: 'helicopter', emoji: '🚁', hint: '直升機', mode: 'listening' },
    { word: 'her', emoji: 'Ⓗ', hint: '她', mode: 'grammar', sentence: 'She is my friend. I like ___.', options: ['her', 'him', 'she', 'he'], correct: 'her', translation: '她是我的朋友。我喜歡她。' },
    { word: 'here', emoji: '🈁', hint: '這裡', mode: 'grammar', sentence: 'Come ___ and play with me.', options: ['here', 'there', 'where', 'everywhere'], correct: 'here', translation: '來這裡和我一起玩。' },
    { word: 'hers', emoji: 'Ⓗ', hint: '她的', mode: 'grammar', sentence: 'This dress is ___.', options: ['hers', 'her', 'she', 'his'], correct: 'hers', translation: '這件洋裝是她的。' },
    { word: 'him', emoji: 'Ⓗ', hint: '他', mode: 'grammar', sentence: 'He is my brother. I love ___.', options: ['him', 'her', 'he', 'his'], correct: 'him', translation: '他是我兄弟。我愛他。' },
    { word: 'hippo', emoji: '🦛', hint: '河馬', mode: 'spell' },
    { word: 'his', emoji: 'Ⓗ', hint: '他的', mode: 'grammar', sentence: 'This is Toby. ___ hat is blue.', options: ['His', 'Her', 'My', 'Your'], correct: 'His', translation: '這是 Toby。他的帽子是藍色的。' },
    { word: 'hit', emoji: 'Ⓗ', hint: '擊中', mode: 'spell' },
    { word: 'hobby', emoji: 'Ⓗ', hint: '嗜好', mode: 'spell' },
    { word: 'hockey', emoji: '🏑', hint: '曲棍球', mode: 'listening' },
    { word: 'hold', emoji: 'Ⓗ', hint: '保持', mode: 'spell' },
    { word: 'home', emoji: 'Ⓗ', hint: '家', mode: 'spell' },
    { word: 'horse', emoji: '🐴', hint: '馬', mode: 'listening' },
    { word: 'house', emoji: '🏠', hint: '房子', mode: 'match' },
    { word: 'I', emoji: 'Ⓘ', hint: '我', mode: 'grammar', sentence: '___ am seven years old.', options: ['I', 'He', 'She', 'We'], correct: 'I', translation: '我七歲。' },
    { word: 'ice cream', emoji: '🍦', hint: '冰淇淋', mode: 'listening' },
    { word: 'in', emoji: 'Ⓘ', hint: '在', mode: 'grammar', sentence: 'The key is ___ the box.', options: ['in', 'on', 'under', 'behind'], correct: 'in', translation: '鑰匙在盒子裡。' },
    { word: 'in front of', emoji: 'Ⓘ', hint: '在前面', mode: 'grammar', sentence: 'The car is parked ___ the house.', options: ['in front of', 'between', 'under', 'in'], correct: 'in front of', translation: '車子停在房子前面。' },
    { word: 'it', emoji: 'Ⓘ', hint: '它', mode: 'grammar', sentence: 'I have a dog. ___ is brown.', options: ['It', 'He', 'She', 'They'], correct: 'It', translation: '我有一隻狗。它是棕色的。' },
    { word: 'its', emoji: 'Ⓘ', hint: '它的', mode: 'grammar', sentence: 'The cat licked ___ paw.', options: ['its', 'it', 'his', 'her'], correct: 'its', translation: '貓舔了牠的爪子。' },
    { word: 'jacket', emoji: 'Ⓙ', hint: '夾克', mode: 'spell' },
    { word: 'jeans', emoji: '👖', hint: '牛仔褲', mode: 'listening' },
    { word: 'jellyfish', emoji: '🪼', hint: '水母', mode: 'match' },
    { word: 'juice', emoji: '🧃', hint: '果汁', mode: 'spell' },
    { word: 'jump', emoji: 'Ⓙ', hint: '跳躍', mode: 'spell' },
    { word: 'keyboard', emoji: '⌨️', hint: '鍵盤（電腦）', mode: 'listening' },
    { word: 'kick', emoji: '🛴', hint: '踢', mode: 'match' },
    { word: 'kid', emoji: '🧒', hint: '孩子', mode: 'match' },
    { word: 'kitchen', emoji: '🍳', hint: '廚房', mode: 'match' },
    { word: 'kite', emoji: '🪁', hint: '風箏', mode: 'spell' },
    { word: 'kiwi', emoji: '🥝', hint: '奇異果', mode: 'match' },
    { word: 'lamp', emoji: '🛋️', hint: '燈', mode: 'match' },
    { word: 'leg', emoji: '🦵', hint: '腿', mode: 'match' },
    { word: 'lemon', emoji: '🍋', hint: '檸檬', mode: 'listening' },
    { word: 'lemonade', emoji: 'Ⓛ', hint: '檸檬水', mode: 'spell' },
    { word: 'let\'s', emoji: 'Ⓛ', hint: '讓我們', mode: 'spell' },
    { word: 'letter', emoji: '🔤', hint: '字母', mode: 'match' },
    { word: 'like', emoji: 'Ⓛ', hint: '喜歡', mode: 'grammar', sentence: 'I ___ eating ice cream.', options: ['like', 'likes', 'liking', 'liked'], correct: 'like', translation: '我喜歡吃冰淇淋。' },
    { word: 'lime', emoji: 'Ⓛ', hint: '石灰', mode: 'spell' },
    { word: 'listen', emoji: 'Ⓛ', hint: '聽', mode: 'spell' },
    { word: 'living room', emoji: '🏡', hint: '客廳', mode: 'match' },
    { word: 'lizard', emoji: '🦎', hint: '蜥蜴', mode: 'match' },
    { word: 'long', emoji: '🥖', hint: '長', mode: 'match' },
    { word: 'look', emoji: '👀', hint: '看看', mode: 'listening' },
    { word: 'look at', emoji: '👁', hint: '看看', mode: 'match' },
    { word: 'lorry', emoji: '🚛', hint: '卡車', mode: 'match' },
    { word: 'lots', emoji: '📦', hint: '許多', mode: 'grammar', sentence: 'We have ___ of toys.', options: ['lots', 'much', 'any', 'a'], correct: 'lots', translation: '我們有許多玩具。' },
    { word: 'lots of', emoji: 'Ⓛ', hint: '很多', mode: 'grammar', sentence: 'There are ___ flowers in the garden.', options: ['lots of', 'much', 'an', 'a'], correct: 'lots of', translation: '花園裡有許多花。' },
    { word: 'love', emoji: '🥰', hint: '愛', mode: 'match' },
    { word: 'lunch', emoji: 'Ⓛ', hint: '午餐', mode: 'spell' },
    { word: 'make', emoji: 'Ⓜ', hint: '使', mode: 'spell' },
    { word: 'man', emoji: 'Ⓜ', hint: '男人', mode: 'spell' },
    { word: 'mango', emoji: '🥭', hint: '芒果', mode: 'match' },
    { word: 'many', emoji: 'Ⓜ', hint: '許多', mode: 'grammar', sentence: 'How ___ pencils do you have?', options: ['many', 'much', 'some', 'any'], correct: 'many', translation: '你有多少支鉛筆？' },
    { word: 'mat', emoji: '▦', hint: '墊子', mode: 'match' },
    { word: 'me', emoji: 'Ⓜ', hint: '我', mode: 'grammar', sentence: 'Please help ___ with my homework.', options: ['me', 'I', 'my', 'mine'], correct: 'me', translation: '請幫我寫功課。' },
    { word: 'meat', emoji: '🍗', hint: '肉', mode: 'listening' },
    { word: 'meatballs', emoji: 'Ⓜ', hint: '肉丸', mode: 'spell' },
    { word: 'milk', emoji: '🍼', hint: '牛奶', mode: 'listening' },
    { word: 'mine', emoji: 'Ⓜ', hint: '我的', mode: 'grammar', sentence: 'This blue bag is ___.', options: ['mine', 'my', 'I', 'me'], correct: 'mine', translation: '這個藍色包包是我的。' },
    { word: 'mirror', emoji: '🪞', hint: '鏡子', mode: 'listening' },
    { word: 'monkey', emoji: '🐒', hint: '猴子', mode: 'listening' },
    { word: 'monster', emoji: '👹', hint: '怪物', mode: 'match' },
    { word: 'morning', emoji: 'Ⓜ', hint: '早安', mode: 'spell' },
    { word: 'mother', emoji: 'Ⓜ', hint: '媽媽', mode: 'spell' },
    { word: 'motorbike', emoji: '🛵', hint: '摩托車', mode: 'spell' },
    { word: 'mouse', emoji: '🖱️', hint: '滑鼠（電腦）', mode: 'spell' },
    { word: 'mouse', emoji: '🐭', hint: '滑鼠', mode: 'listening' },
    { word: 'mouth', emoji: '👄', hint: '嘴', mode: 'listening' },
    { word: 'mum', emoji: '👩', hint: '媽媽', mode: 'listening' },
    { word: 'music', emoji: '🎶', hint: '音樂', mode: 'listening' },
    { word: 'name', emoji: 'Ⓝ', hint: '姓名', mode: 'spell' },
    { word: 'new', emoji: '🆕', hint: '新的', mode: 'match' },
    { word: 'next to', emoji: 'Ⓝ', hint: '旁邊', mode: 'grammar', sentence: 'The chair is ___ the desk.', options: ['next to', 'under', 'between', 'in'], correct: 'next to', translation: '椅子在書桌旁邊。' },
    { word: 'nice', emoji: 'Ⓝ', hint: '不錯', mode: 'spell' },
    { word: 'night', emoji: 'Ⓝ', hint: '晚上', mode: 'spell' },
    { word: 'nine', emoji: '9️⃣', hint: '九', mode: 'match' },
    { word: 'nineteen', emoji: 'Ⓝ', hint: '十九', mode: 'spell' },
    { word: 'no', emoji: 'Ⓝ', hint: '不', mode: 'grammar', sentence: 'There are ___ apples left.', options: ['no', 'not', 'any', 'none'], correct: 'no', translation: '沒有剩餘的蘋果了。' },
    { word: 'nose', emoji: '👃', hint: '鼻子', mode: 'listening' },
    { word: 'not', emoji: 'Ⓝ', hint: '不', mode: 'spell' },
    { word: 'now', emoji: 'Ⓝ', hint: '現在', mode: 'spell' },
    { word: 'number', emoji: '#️⃣', hint: '數量', mode: 'listening' },
    { word: 'of', emoji: 'Ⓞ', hint: '的', mode: 'grammar', sentence: 'He gave me a cup ___ water.', options: ['of', 'to', 'for', 'with'], correct: 'of', translation: '他給了我一杯水。' },
    { word: 'OK', emoji: '🆗', hint: '好的', mode: 'match' },
    { word: 'old', emoji: '👴', hint: '老', mode: 'listening' },
    { word: 'on', emoji: '🔛', hint: '上', mode: 'grammar', sentence: 'The book is ___ the desk.', options: ['on', 'under', 'in', 'behind'], correct: 'on', translation: '書在書桌上。' },
    { word: 'one', emoji: '1️⃣', hint: '一', mode: 'grammar', sentence: 'I have only ___ sister.', options: ['one', 'two', 'many', 'first'], correct: 'one', translation: '我只有一個姐姐。' },
    { word: 'onion', emoji: '🧅', hint: '洋蔥', mode: 'listening' },
    { word: 'open', emoji: 'Ⓞ', hint: '打開', mode: 'spell' },
    { word: 'or', emoji: 'Ⓞ', hint: '或', mode: 'grammar', sentence: 'Do you want juice ___ milk?', options: ['or', 'and', 'but', 'so'], correct: 'or', translation: '你想要果汁還是牛奶？' },
    { word: 'orange', emoji: '🍊', hint: '橘色', mode: 'match' },
    { word: 'ours', emoji: 'Ⓞ', hint: '我們的', mode: 'grammar', sentence: 'This classroom is ___.', options: ['ours', 'our', 'we', 'us'], correct: 'ours', translation: '這間教室是我們的。' },
    { word: 'page', emoji: 'Ⓟ', hint: '頁面', mode: 'spell' },
    { word: 'painting', emoji: 'Ⓟ', hint: '繪畫', mode: 'spell' },
    { word: 'paper', emoji: '📄', hint: '紙', mode: 'match' },
    { word: 'park', emoji: '🛝', hint: '公園', mode: 'match' },
    { word: 'part', emoji: 'Ⓟ', hint: '部分', mode: 'spell' },
    { word: 'pea', emoji: 'Ⓟ', hint: '豌豆', mode: 'spell' },
    { word: 'pear', emoji: '🍐', hint: '梨', mode: 'match' },
    { word: 'pen', emoji: '🖊️', hint: '筆', mode: 'listening' },
    { word: 'pencil', emoji: '✏', hint: '鉛筆', mode: 'listening' },
    { word: 'person', emoji: 'Ⓟ', hint: '人', mode: 'spell' },
    { word: 'pet', emoji: 'Ⓟ', hint: '寵物', mode: 'spell' },
    { word: 'phone', emoji: '☎️', hint: '電話', mode: 'match' },
    { word: 'photo', emoji: 'Ⓟ', hint: '照片', mode: 'spell' },
    { word: 'piano', emoji: '🎹', hint: '鋼琴', mode: 'listening' },
    { word: 'picture', emoji: '🖼️', hint: '圖片', mode: 'match' },
    { word: 'pie', emoji: '🥧', hint: '派', mode: 'match' },
    { word: 'pineapple', emoji: '🍍', hint: '鳳梨', mode: 'match' },
    { word: 'pink', emoji: '💗', hint: '粉紅色', mode: 'match' },
    { word: 'plane', emoji: '✈', hint: '飛機', mode: 'match' },
    { word: 'play', emoji: '🎮', hint: '玩', mode: 'match' },
    { word: 'playground', emoji: 'Ⓟ', hint: '遊樂場', mode: 'spell' },
    { word: 'point', emoji: 'Ⓟ', hint: '點', mode: 'spell' },
    { word: 'polar bear', emoji: '🐻‍❄️', hint: '北極熊', mode: 'match' },
    { word: 'poster', emoji: 'Ⓟ', hint: '海報', mode: 'spell' },
    { word: 'potato', emoji: '🥔', hint: '馬鈴薯', mode: 'listening' },
    { word: 'purple', emoji: '🟣', hint: '紫色', mode: 'match' },
    { word: 'put', emoji: 'Ⓟ', hint: '把', mode: 'spell' },
    { word: 'question', emoji: '❓', hint: '問題', mode: 'match' },
    { word: 'radio', emoji: '📻', hint: '收音機', mode: 'listening' },
    { word: 'read', emoji: '📚', hint: '讀', mode: 'match' },
    { word: 'really', emoji: 'Ⓡ', hint: '真的', mode: 'grammar', sentence: 'I am ___ happy today.', options: ['really', 'real', 'more', 'too'], correct: 'really', translation: '我今天真的很開心。' },
    { word: 'red', emoji: '🔴', hint: '紅色', mode: 'listening' },
    { word: 'rice', emoji: '🍚', hint: '米飯', mode: 'listening' },
    { word: 'ride', emoji: '🚴', hint: '騎', mode: 'match' },
    { word: 'right', emoji: '🗯️', hint: '正確（正確）', mode: 'grammar', sentence: 'My house is on the ___ side.', options: ['right', 'left', 'middle', 'front'], correct: 'right', translation: '我家在右邊。' },
    { word: 'robot', emoji: '🤖', hint: '機器人', mode: 'match' },
    { word: 'room', emoji: '🚪', hint: '房間', mode: 'listening' },
    { word: 'rubber', emoji: '🧼', hint: '橡皮擦', mode: 'match' },
    { word: 'rug', emoji: 'Ⓡ', hint: '地毯', mode: 'spell' },
    { word: 'ruler', emoji: '📏', hint: '尺子', mode: 'match' },
    { word: 'run', emoji: '🏃', hint: '跑', mode: 'listening' },
    { word: 'sad', emoji: '😢', hint: '悲傷', mode: 'match' },
    { word: 'sand', emoji: '🏖', hint: '沙子', mode: 'match' },
    { word: 'sausage', emoji: '🌭', hint: '香腸', mode: 'listening' },
    { word: 'say', emoji: 'Ⓢ', hint: '說', mode: 'spell' },
    { word: 'scary', emoji: '👻', hint: '可怕的', mode: 'match' },
    { word: 'school', emoji: '👨‍🏫', hint: '學校', mode: 'match' },
    { word: 'sea', emoji: '🐳', hint: '海', mode: 'listening' },
    { word: 'see', emoji: 'Ⓢ', hint: '看到', mode: 'spell' },
    { word: 'sentence', emoji: 'Ⓢ', hint: '句子', mode: 'spell' },
    { word: 'seven', emoji: '7️⃣', hint: '七', mode: 'listening' },
    { word: 'seventeen', emoji: 'Ⓢ', hint: '十七', mode: 'spell' },
    { word: 'she', emoji: 'Ⓢ', hint: '她', mode: 'grammar', sentence: 'This is my mother. ___ is cooking.', options: ['She', 'He', 'It', 'They'], correct: 'She', translation: '這是我媽媽。她正在做飯。' },
    { word: 'sheep', emoji: '🐑', hint: '羊', mode: 'listening' },
    { word: 'shell', emoji: 'Ⓢ', hint: '外殼', mode: 'spell' },
    { word: 'ship', emoji: '🚢', hint: '船', mode: 'match' },
    { word: 'shirt', emoji: '👕', hint: '襯衫', mode: 'match' },
    { word: 'shoe', emoji: '👞', hint: '鞋', mode: 'listening' },
    { word: 'shop', emoji: 'Ⓢ', hint: '商店', mode: 'spell' },
    { word: 'short', emoji: 'Ⓢ', hint: '短', mode: 'spell' },
    { word: 'shorts', emoji: '🩳', hint: '短褲', mode: 'listening' },
    { word: 'show', emoji: 'Ⓢ', hint: '顯示', mode: 'spell' },
    { word: 'silly', emoji: '😜', hint: '愚蠢的', mode: 'listening' },
    { word: 'sing', emoji: '🎤', hint: '唱歌', mode: 'listening' },
    { word: 'sister', emoji: '👭', hint: '妹妹', mode: 'match' },
    { word: 'sit', emoji: 'Ⓢ', hint: '坐', mode: 'spell' },
    { word: 'six', emoji: '6️⃣', hint: '六', mode: 'match' },
    { word: 'sixteen', emoji: 'Ⓢ', hint: '十六', mode: 'spell' },
    { word: 'skateboard', emoji: '🛹', hint: '滑板', mode: 'match' },
    { word: 'skateboarding', emoji: 'Ⓢ', hint: '滑板', mode: 'spell' },
    { word: 'skirt', emoji: 'Ⓢ', hint: '裙子', mode: 'spell' },
    { word: 'sleep', emoji: 'Ⓢ', hint: '睡覺', mode: 'spell' },
    { word: 'small', emoji: 'Ⓢ', hint: '小', mode: 'spell' },
    { word: 'smile', emoji: '😊', hint: '微笑', mode: 'match' },
    { word: 'snake', emoji: '🐍', hint: '蛇', mode: 'match' },
    { word: 'sock', emoji: 'Ⓢ', hint: '襪子', mode: 'spell' },
    { word: 'sofa', emoji: '🛋', hint: '沙發', mode: 'listening' },
    { word: 'some', emoji: 'Ⓢ', hint: '一些', mode: 'grammar', sentence: 'Would you like ___ milk?', options: ['some', 'any', 'many', 'a'], correct: 'some', translation: '你想要來點牛奶嗎？' },
    { word: 'song', emoji: 'Ⓢ', hint: '歌曲', mode: 'spell' },
    { word: 'sorry', emoji: 'Ⓢ', hint: '抱歉', mode: 'spell' },
    { word: 'spider', emoji: '🕷️', hint: '蜘蛛', mode: 'listening' },
    { word: 'sport', emoji: '👟', hint: '運動', mode: 'match' },
    { word: 'stand', emoji: 'Ⓢ', hint: '站', mode: 'spell' },
    { word: 'start', emoji: 'Ⓢ', hint: '開始', mode: 'spell' },
    { word: 'stop', emoji: '🚏', hint: '停止', mode: 'match' },
    { word: 'street', emoji: 'Ⓢ', hint: '街道', mode: 'spell' },
    { word: 'sun', emoji: '🌞', hint: '太陽', mode: 'match' },
    { word: 'swim', emoji: 'Ⓢ', hint: '游泳', mode: 'spell' },
    { word: 'table', emoji: 'Ⓣ', hint: '桌子', mode: 'spell' },
    { word: 'table tennis', emoji: 'Ⓣ', hint: '乒乓球', mode: 'spell' },
    { word: 'tail', emoji: 'Ⓣ', hint: '尾巴', mode: 'spell' },
    { word: 'take a photo / picture', emoji: 'Ⓣ', hint: '拍照/拍照', mode: 'spell' },
    { word: 'talk', emoji: '🗨', hint: '談話', mode: 'match' },
    { word: 'teacher', emoji: '🧑‍🏫', hint: '老師', mode: 'match' },
    { word: 'teddy bear', emoji: '🧸', hint: '泰迪熊', mode: 'match' },
    { word: 'television', emoji: '📺', hint: '電視', mode: 'spell' },
    { word: 'tell', emoji: 'Ⓣ', hint: '告訴', mode: 'spell' },
    { word: 'ten', emoji: '🔟', hint: '十', mode: 'listening' },
    { word: 'tennis', emoji: '🎾', hint: '網球', mode: 'listening' },
    { word: 'tennis racket', emoji: 'Ⓣ', hint: '網球拍', mode: 'spell' },
    { word: 'that', emoji: 'Ⓣ', hint: '那個', mode: 'grammar', sentence: 'Look at ___ bird up in the tree.', options: ['that', 'this', 'these', 'those'], correct: 'that', translation: '看樹上的那隻鳥。' },
    { word: 'the', emoji: 'Ⓣ', hint: '的', mode: 'grammar', sentence: '___ sun is shining brightly.', options: ['The', 'A', 'An', 'Some'], correct: 'The', translation: '太陽正明亮地照耀著。' },
    { word: 'theirs', emoji: 'Ⓣ', hint: '他們的', mode: 'grammar', sentence: 'This house is ___.', options: ['theirs', 'their', 'they', 'them'], correct: 'theirs', translation: '這間房子是他們的。' },
    { word: 'them', emoji: 'Ⓣ', hint: '他們', mode: 'grammar', sentence: 'They are my cousins. I like ___.', options: ['them', 'they', 'their', 'theirs'], correct: 'them', translation: '他們是我的堂表親。我喜歡他們。' },
    { word: 'there', emoji: 'Ⓣ', hint: '那裡', mode: 'grammar', sentence: 'The playground is over ___.', options: ['there', 'here', 'where', 'under'], correct: 'there', translation: '遊樂場在那邊。' },
    { word: 'these', emoji: 'Ⓣ', hint: '這些', mode: 'grammar', sentence: '___ books in my hands are heavy.', options: ['These', 'This', 'That', 'Those'], correct: 'these', translation: '我手上的這些書很重。' },
    { word: 'they', emoji: 'Ⓣ', hint: '他們', mode: 'grammar', sentence: 'My friends are here. ___ are playing.', options: ['They', 'He', 'She', 'We'], correct: 'They', translation: '我的朋友們在這裡。他們正在玩耍。' },
    { word: 'thing', emoji: 'Ⓣ', hint: '東西', mode: 'spell' },
    { word: 'thirteen', emoji: 'Ⓣ', hint: '十三', mode: 'spell' },
    { word: 'this', emoji: 'Ⓣ', hint: '這個', mode: 'grammar', sentence: '___ apple in my hand is red.', options: ['This', 'These', 'That', 'Those'], correct: 'This', translation: '我手上的這顆蘋果是紅色的。' },
    { word: 'those', emoji: 'Ⓣ', hint: '那些', mode: 'grammar', sentence: 'Look at ___ stars in the sky.', options: ['those', 'this', 'that', 'these'], correct: 'those', translation: '看天空中的那些星星。' },
    { word: 'three', emoji: '3️⃣', hint: '三', mode: 'match' },
    { word: 'throw', emoji: 'Ⓣ', hint: '丟', mode: 'spell' },
    { word: 'tick', emoji: '✅', hint: '勾選', mode: 'listening' },
    { word: 'tiger', emoji: '🐯', hint: '老虎', mode: 'listening' },
    { word: 'to', emoji: 'Ⓣ', hint: '到', mode: 'grammar', sentence: 'We walk ___ school every day.', options: ['to', 'at', 'in', 'for'], correct: 'to', translation: '我們每天走路去學校。' },
    { word: 'today', emoji: 'Ⓣ', hint: '今天', mode: 'spell' },
    { word: 'tomato', emoji: '🍅', hint: '番茄', mode: 'match' },
    { word: 'too', emoji: '🙋', hint: '也', mode: 'match' },
    { word: 'toy', emoji: 'Ⓣ', hint: '玩具', mode: 'spell' },
    { word: 'train', emoji: '🚋', hint: '火車', mode: 'match' },
    { word: 'tree', emoji: '🌲', hint: '樹', mode: 'match' },
    { word: 'trousers', emoji: 'Ⓣ', hint: '褲子', mode: 'spell' },
    { word: 'try', emoji: 'Ⓣ', hint: '嘗試', mode: 'spell' },
    { word: 'T-shirt', emoji: 'Ⓣ', hint: 'T卹', mode: 'spell' },
    { word: 'twelve', emoji: 'Ⓣ', hint: '十二', mode: 'spell' },
    { word: 'twenty', emoji: 'Ⓣ', hint: '二十', mode: 'spell' },
    { word: 'two', emoji: '2️⃣', hint: '兩個', mode: 'match' },
    { word: 'ugly', emoji: '👹', hint: '醜陋', mode: 'listening' },
    { word: 'under', emoji: '🔞', hint: '下', mode: 'grammar', sentence: 'The cat is sleeping ___ the table.', options: ['under', 'on', 'in', 'between'], correct: 'under', translation: '貓正在桌子底下睡覺。' },
    { word: 'understand', emoji: 'Ⓤ', hint: '明白', mode: 'spell' },
    { word: 'us', emoji: 'Ⓤ', hint: '我們', mode: 'grammar', sentence: 'Teacher told ___ a story.', options: ['us', 'we', 'our', 'ours'], correct: 'us', translation: '老師給我們講了一個故事。' },
    { word: 'walk', emoji: 'Ⓦ', hint: '行人徒步區', mode: 'spell' },
    { word: 'wall', emoji: '🧱', hint: '牆', mode: 'match' },
    { word: 'want', emoji: 'Ⓦ', hint: '想要', mode: 'spell' },
    { word: 'watch', emoji: 'Ⓦ', hint: '手錶（手腕）', mode: 'spell' },
    { word: 'watch', emoji: '⌚', hint: '看（電視）', mode: 'listening' },
    { word: 'water', emoji: '💦', hint: '水', mode: 'listening' },
    { word: 'watermelon', emoji: '🍉', hint: '西瓜', mode: 'match' },
    { word: 'we', emoji: 'Ⓦ', hint: '我們', mode: 'grammar', sentence: 'My brother and I are tall. ___ like basketball.', options: ['We', 'They', 'He', 'She'], correct: 'We', translation: '我哥哥和我都很高。我們喜歡籃球。' },
    { word: 'wear', emoji: 'Ⓦ', hint: '磨損', mode: 'spell' },
    { word: 'white', emoji: '⚪', hint: '白色', mode: 'listening' },
    { word: 'window', emoji: '🪟', hint: '窗戶', mode: 'match' },
    { word: 'with', emoji: 'Ⓦ', hint: '與', mode: 'grammar', sentence: 'I play games ___ my friends.', options: ['with', 'to', 'for', 'at'], correct: 'with', translation: '我和我的朋友們一起玩遊戲。' },
    { word: 'woman', emoji: '👩', hint: '女人', mode: 'match' },
    { word: 'word', emoji: 'Ⓦ', hint: '字', mode: 'spell' },
    { word: 'would like', emoji: 'Ⓦ', hint: '想要', mode: 'spell' },
    { word: 'write', emoji: 'Ⓦ', hint: '寫', mode: 'spell' },
    { word: 'year', emoji: 'Ⓨ', hint: '年', mode: 'spell' },
    { word: 'yellow', emoji: '🟡', hint: '黃色', mode: 'match' },
    { word: 'yes', emoji: 'Ⓨ', hint: '是的', mode: 'spell' },
    { word: 'you', emoji: 'Ⓨ', hint: '你', mode: 'grammar', sentence: '___ are my best friend.', options: ['You', 'He', 'She', 'It'], correct: 'you', translation: '你是我的好朋友。' },
    { word: 'young', emoji: '👼', hint: '年輕的', mode: 'match' },
    { word: 'yours', emoji: 'Ⓨ', hint: '你的', mode: 'grammar', sentence: 'Is this pen ___?', options: ['yours', 'your', 'you', 'my'], correct: 'yours', translation: '這支筆是你的嗎？' },
    { word: 'zebra', emoji: '🦓', hint: '斑馬', mode: 'match' },
    { word: 'zoo', emoji: 'Ⓩ', hint: '動物園', mode: 'spell' },
    { word: 'after', emoji: 'Ⓐ', hint: '之後', mode: 'grammar', sentence: 'We went home ___ the movie finished.', options: ['after', 'before', 'than', 'during'], correct: 'after', translation: '電影結束後我們回家了。' },
    { word: 'all', emoji: 'Ⓐ', hint: '全部', mode: 'grammar', sentence: '___ the students are in the classroom.', options: ['All', 'Every', 'Some', 'Any'], correct: 'All', translation: '所有的學生都在教室裡。' },
    { word: 'always', emoji: 'Ⓐ', hint: '總是', mode: 'spell' },
    { word: 'another', emoji: 'Ⓐ', hint: '另一個', mode: 'grammar', sentence: 'Can I have ___ glass of milk?', options: ['another', 'other', 'others', 'some'], correct: 'another', translation: '我可以再要一杯牛奶嗎？' },
    { word: 'back', emoji: '🔙', hint: '回來', mode: 'listening' },
    { word: 'bad', emoji: 'Ⓑ', hint: '壞', mode: 'spell' },
    { word: 'buy', emoji: '🛒', hint: '買', mode: 'match' },
    { word: 'carry', emoji: 'Ⓒ', hint: '攜帶', mode: 'spell' },
    { word: 'city', emoji: '🏙️', hint: '城市', mode: 'listening' },
    { word: 'climb', emoji: 'Ⓒ', hint: '攀爬', mode: 'spell' },
    { word: 'cloud', emoji: '☁️', hint: '雲', mode: 'listening' },
    { word: 'coat', emoji: '🧥', hint: '外套', mode: 'listening' },
    { word: 'cold', emoji: '❄️', hint: '冷', mode: 'match' },
    { word: 'cook', emoji: '🧑‍🍳', hint: '廚師', mode: 'match' },
    { word: 'dance', emoji: 'Ⓓ', hint: '跳舞', mode: 'spell' },
    { word: 'dream', emoji: 'Ⓓ', hint: '夢想', mode: 'spell' },
    { word: 'email', emoji: '📧', hint: '電子郵件', mode: 'match' },
    { word: 'every', emoji: 'Ⓔ', hint: '每個', mode: 'grammar', sentence: 'I go swimming ___ Saturday.', options: ['every', 'all', 'some', 'any'], correct: 'every', translation: '我每個星期六都去游泳。' },
    { word: 'fall', emoji: 'Ⓕ', hint: '跌倒（下）', mode: 'spell' },
    { word: 'famous', emoji: 'Ⓕ', hint: '著名的', mode: 'spell' },
    { word: 'farm', emoji: 'Ⓕ', hint: '農場', mode: 'spell' },
    { word: 'farmer', emoji: '🧑‍🌾', hint: '農民', mode: 'listening' },
    { word: 'fat', emoji: 'Ⓕ', hint: '脂肪', mode: 'spell' },
    { word: 'fine', emoji: 'Ⓕ', hint: '很好', mode: 'spell' },
    { word: 'first', emoji: '🥇', hint: '第一', mode: 'match' },
    { word: 'laugh', emoji: '😄', hint: '笑', mode: 'listening' },
    { word: 'lion', emoji: '🦁', hint: '獅子', mode: 'match' },
    { word: 'little', emoji: 'Ⓛ', hint: '很少', mode: 'spell' },
    { word: 'rabbit', emoji: '🐰', hint: '兔子', mode: 'match' },
    { word: 'send', emoji: 'Ⓢ', hint: '傳送', mode: 'spell' },
    { word: 'sky', emoji: 'Ⓢ', hint: '天空', mode: 'spell' },
    { word: 'son', emoji: '👦', hint: '兒子', mode: 'match' },
    { word: 'star', emoji: '⭐', hint: '星星／明星', mode: 'listening' },
    { word: 'sunny', emoji: '☀️', hint: '陽光明媚', mode: 'listening' }
  ],
  movers: [
    { word: 'above', emoji: 'Ⓐ', hint: '上面', mode: 'grammar', sentence: 'The clock is hanging ___ the door.', options: ['above', 'under', 'between', 'through'], correct: 'above', translation: '時鐘掛在門的上方。' },
    { word: 'address', emoji: 'Ⓐ', hint: '地址', mode: 'spell' },
    { word: 'afraid', emoji: '😨', hint: '害怕', mode: 'listening' },
    { word: 'age', emoji: 'Ⓐ', hint: '年齡', mode: 'spell' },
    { word: 'all right', emoji: 'Ⓐ', hint: '好吧', mode: 'spell' },
    { word: 'along', emoji: 'Ⓐ', hint: '沿著', mode: 'grammar', sentence: 'We walked ___ the riverbank.', options: ['along', 'across', 'through', 'into'], correct: 'along', translation: '我們沿著河岸散步。' },
    { word: 'any', emoji: 'Ⓐ', hint: '任何', mode: 'grammar', sentence: 'Do you have ___ questions?', options: ['any', 'some', 'many', 'much'], correct: 'any', translation: '你有任何問題嗎？' },
    { word: 'app', emoji: 'Ⓐ', hint: '應用程式', mode: 'spell' },
    { word: 'around', emoji: 'Ⓐ', hint: '周圍', mode: 'grammar', sentence: 'We ran ___ the playground.', options: ['around', 'through', 'under', 'above'], correct: 'around', translation: '我們圍著遊樂場跑。' },
    { word: 'asleep', emoji: 'Ⓐ', hint: '睡著了', mode: 'spell' },
    { word: 'aunt', emoji: 'Ⓐ', hint: '阿姨', mode: 'spell' },
    { word: 'awake', emoji: 'Ⓐ', hint: '醒著', mode: 'spell' },
    { word: 'badly', emoji: 'Ⓑ', hint: '嚴重地', mode: 'spell' },
    { word: 'balcony', emoji: 'Ⓑ', hint: '陽台', mode: 'spell' },
    { word: 'band', emoji: 'Ⓑ', hint: '樂隊（音樂）', mode: 'spell' },
    { word: 'basement', emoji: 'Ⓑ', hint: '地下室', mode: 'spell' },
    { word: 'bat', emoji: '🦇', hint: '蝙蝠', mode: 'listening' },
    { word: 'be called', emoji: 'Ⓑ', hint: '被稱為', mode: 'spell' },
    { word: 'beard', emoji: '🧔', hint: '鬍鬚', mode: 'match' },
    { word: 'because', emoji: 'Ⓑ', hint: '因為', mode: 'grammar', sentence: 'I stayed inside ___ it was raining.', options: ['because', 'but', 'so', 'than'], correct: 'because', translation: '我待在室內，因為下雨了。' },
    { word: 'before', emoji: 'Ⓑ', hint: '之前', mode: 'grammar', sentence: 'Wash your hands ___ eating dinner.', options: ['before', 'after', 'than', 'during'], correct: 'before', translation: '吃晚餐前要洗手。' },
    { word: 'below', emoji: 'Ⓑ', hint: '下面', mode: 'grammar', sentence: 'The temperature is ___ zero today.', options: ['below', 'above', 'under', 'between'], correct: 'below', translation: '今天的溫度低於零度。' },
    { word: 'best', emoji: 'Ⓑ', hint: '最好的', mode: 'spell' },
    { word: 'better', emoji: 'Ⓑ', hint: '更好', mode: 'spell' },
    { word: 'blanket', emoji: 'Ⓑ', hint: '毯子', mode: 'spell' },
    { word: 'blond', emoji: '👱', hint: '金髮的', mode: 'listening' },
    { word: 'boring', emoji: 'Ⓑ', hint: '無聊的', mode: 'spell' },
    { word: 'both', emoji: 'Ⓑ', hint: '兩者', mode: 'grammar', sentence: '___ of my brothers like football.', options: ['Both', 'All', 'Every', 'Each'], correct: 'Both', translation: '我的兩個兄弟都喜歡足球。' },
    { word: 'bottle', emoji: '🍾', hint: '瓶子', mode: 'match' },
    { word: 'bottom', emoji: 'Ⓑ', hint: '底部', mode: 'spell' },
    { word: 'bowl', emoji: '🥣', hint: '碗', mode: 'match' },
    { word: 'brave', emoji: 'Ⓑ', hint: '勇敢的', mode: 'spell' },
    { word: 'brilliant', emoji: 'Ⓑ', hint: '輝煌的', mode: 'spell' },
    { word: 'bring', emoji: 'Ⓑ', hint: '帶', mode: 'spell' },
    { word: 'build', emoji: 'Ⓑ', hint: '建造', mode: 'spell' },
    { word: 'building', emoji: '🏛️', hint: '建築物', mode: 'match' },
    { word: 'bus station', emoji: 'Ⓑ', hint: '公車站', mode: 'spell' },
    { word: 'bus stop', emoji: '🚏', hint: '巴士站', mode: 'match' },
    { word: 'busy', emoji: 'Ⓑ', hint: '忙', mode: 'spell' },
    { word: 'by', emoji: 'Ⓑ', hint: '透過', mode: 'grammar', sentence: 'He travels to work ___ bus.', options: ['by', 'with', 'on', 'at'], correct: 'by', translation: '他搭公車去上班。' },
    { word: 'café', emoji: 'Ⓒ', hint: '咖啡廳', mode: 'spell' },
    { word: 'cage', emoji: 'Ⓒ', hint: '籠子', mode: 'spell' },
    { word: 'call', emoji: 'Ⓒ', hint: '打電話', mode: 'spell' },
    { word: 'car park', emoji: 'Ⓒ', hint: '停車場', mode: 'spell' },
    { word: 'careful', emoji: 'Ⓒ', hint: '小心', mode: 'spell' },
    { word: 'carefully', emoji: 'Ⓒ', hint: '仔細地', mode: 'spell' },
    { word: 'catch', emoji: 'Ⓒ', hint: '趕上（公共汽車）', mode: 'spell' },
    { word: 'CD', emoji: '💿', hint: '光碟', mode: 'listening' },
    { word: 'centre', emoji: 'Ⓒ', hint: '中心', mode: 'spell' },
    { word: 'change', emoji: 'Ⓒ', hint: '改變', mode: 'spell' },
    { word: 'cheese', emoji: '🧀', hint: '起司', mode: 'listening' },
    { word: 'cinema', emoji: '🎦', hint: '電影院', mode: 'listening' },
    { word: 'circle', emoji: '⭕', hint: '圓圈', mode: 'match' },
    { word: 'circus', emoji: '🎪', hint: '馬戲團', mode: 'listening' },
    { word: 'city center', emoji: 'Ⓒ', hint: '市中心', mode: 'spell' },
    { word: 'clever', emoji: 'Ⓒ', hint: '聰明', mode: 'spell' },
    { word: 'cloudy', emoji: 'Ⓒ', hint: '多雲', mode: 'spell' },
    { word: 'clown', emoji: '🤡', hint: '小丑', mode: 'listening' },
    { word: 'coffee', emoji: '☕', hint: '咖啡', mode: 'match' },
    { word: 'comic', emoji: 'Ⓒ', hint: '漫畫', mode: 'spell' },
    { word: 'comic book', emoji: 'Ⓒ', hint: '漫畫書', mode: 'spell' },
    { word: 'cough', emoji: '🤧', hint: '咳嗽', mode: 'match' },
    { word: 'country', emoji: 'Ⓒ', hint: '國家', mode: 'spell' },
    { word: 'countryside', emoji: 'Ⓒ', hint: '鄉村', mode: 'spell' },
    { word: 'cry', emoji: '😢', hint: '哭', mode: 'match' },
    { word: 'cup', emoji: 'Ⓒ', hint: '杯子', mode: 'spell' },
    { word: 'curly', emoji: '👨‍🦱', hint: '捲曲的', mode: 'listening' },
    { word: 'dangerous', emoji: '⚠', hint: '危險的', mode: 'match' },
    { word: 'daughter', emoji: '👧', hint: '女兒', mode: 'match' },
    { word: 'dentist', emoji: 'Ⓓ', hint: '牙醫', mode: 'spell' },
    { word: 'difference', emoji: 'Ⓓ', hint: '差異', mode: 'spell' },
    { word: 'different', emoji: 'Ⓓ', hint: '不同的', mode: 'spell' },
    { word: 'difficult', emoji: 'Ⓓ', hint: '困難', mode: 'spell' },
    { word: 'doctor', emoji: '👨‍⚕️', hint: '醫生', mode: 'listening' },
    { word: 'dolphin', emoji: '🐬', hint: '海豚', mode: 'match' },
    { word: 'down', emoji: '🙃', hint: '向下', mode: 'grammar', sentence: 'The leaves are falling ___ from the tree.', options: ['down', 'up', 'over', 'through'], correct: 'down', translation: '葉子正從樹上掉落下來。' },
    { word: 'downstairs', emoji: 'Ⓓ', hint: '樓下', mode: 'grammar', sentence: 'Go ___ to find your shoes.', options: ['downstairs', 'upstairs', 'inside', 'outside'], correct: 'downstairs', translation: '去樓下找你的鞋子。' },
    { word: 'dress up', emoji: 'Ⓓ', hint: '打扮', mode: 'spell' },
    { word: 'driver', emoji: 'Ⓓ', hint: '司機', mode: 'spell' },
    { word: 'drop', emoji: '🩸', hint: '掉落', mode: 'listening' },
    { word: 'dry', emoji: 'Ⓓ', hint: '幹', mode: 'spell' },
    { word: 'DVD', emoji: '📀', hint: '光碟', mode: 'match' },
    { word: 'earache', emoji: '🤕', hint: '耳痛', mode: 'listening' },
    { word: 'easy', emoji: 'Ⓔ', hint: '容易', mode: 'spell' },
    { word: 'e-book', emoji: 'Ⓔ', hint: '電子書', mode: 'spell' },
    { word: 'eighteenth', emoji: 'Ⓔ', hint: '第十八', mode: 'spell' },
    { word: 'eighth', emoji: 'Ⓔ', hint: '第八', mode: 'spell' },
    { word: 'eighty', emoji: 'Ⓔ', hint: '八十', mode: 'spell' },
    { word: 'eleventh', emoji: 'Ⓔ', hint: '第十一', mode: 'spell' },
    { word: 'everyone', emoji: 'Ⓔ', hint: '大家', mode: 'grammar', sentence: '___ is smiling at the party.', options: ['Everyone', 'Someone', 'No one', 'Everything'], correct: 'Everyone', translation: '派對上的每個人都在微笑。' },
    { word: 'everything', emoji: 'Ⓔ', hint: '一切', mode: 'grammar', sentence: '___ in this shop is very cheap.', options: ['Everything', 'Everyone', 'Something', 'Nothing'], correct: 'everything', translation: '這家店裡的一切都很便宜。' },
    { word: 'exciting', emoji: 'Ⓔ', hint: '令人興奮的', mode: 'spell' },
    { word: 'fair', emoji: 'Ⓕ', hint: '公平', mode: 'spell' },
    { word: 'feed', emoji: 'Ⓕ', hint: '飼料', mode: 'spell' },
    { word: 'field', emoji: '🏑', hint: '領域', mode: 'match' },
    { word: 'fifteenth', emoji: 'Ⓕ', hint: '第十五', mode: 'spell' },
    { word: 'fifth', emoji: 'Ⓕ', hint: '第五', mode: 'spell' },
    { word: 'fifty', emoji: 'Ⓕ', hint: '五十', mode: 'spell' },
    { word: 'film', emoji: '🎥', hint: '電影', mode: 'match' },
    { word: 'fish', emoji: '🐟', hint: '魚（活動）', mode: 'match' },
    { word: 'fix', emoji: 'Ⓕ', hint: '修復', mode: 'spell' },
    { word: 'forest', emoji: 'Ⓕ', hint: '森林', mode: 'spell' },
    { word: 'forty', emoji: 'Ⓕ', hint: '四十', mode: 'spell' },
    { word: 'fourteenth', emoji: '1️⃣4️⃣', hint: '第十四', mode: 'spell' },
    { word: 'fourth', emoji: 'Ⓕ', hint: '第四', mode: 'spell' },
    { word: 'Friday', emoji: 'Ⓕ', hint: '週五', mode: 'spell' },
    { word: 'frightened', emoji: '😨', hint: '害怕', mode: 'match' },
    { word: 'funfair', emoji: 'Ⓕ', hint: '遊樂場', mode: 'spell' },
    { word: 'get dressed', emoji: '👕', hint: '穿好衣服', mode: 'match' },
    { word: 'get off', emoji: 'Ⓖ', hint: '下車', mode: 'spell' },
    { word: 'get on', emoji: 'Ⓖ', hint: '上車', mode: 'spell' },
    { word: 'get undressed', emoji: '👖', hint: '脫掉衣服', mode: 'listening' },
    { word: 'get up', emoji: '🛌', hint: '起床', mode: 'listening' },
    { word: 'go shopping', emoji: 'Ⓖ', hint: '去購物', mode: 'spell' },
    { word: 'goal', emoji: '🥅', hint: '目標', mode: 'listening' },
    { word: 'granddaughter', emoji: 'Ⓖ', hint: '孫女', mode: 'spell' },
    { word: 'grandparent', emoji: 'Ⓖ', hint: '祖父母', mode: 'spell' },
    { word: 'grandson', emoji: 'Ⓖ', hint: '孫子', mode: 'spell' },
    { word: 'grass', emoji: 'Ⓖ', hint: '草', mode: 'spell' },
    { word: 'ground', emoji: '⛱️', hint: '地面', mode: 'listening' },
    { word: 'grow', emoji: 'Ⓖ', hint: '成長', mode: 'spell' },
    { word: 'grown-up', emoji: 'Ⓖ', hint: '長大了', mode: 'spell' },
    { word: 'have to', emoji: 'Ⓗ', hint: '必須[必須]', mode: 'spell' },
    { word: 'headache', emoji: '🤕', hint: '頭痛', mode: 'listening' },
    { word: 'helmet', emoji: '👷', hint: '頭盔', mode: 'listening' },
    { word: 'help', emoji: '🆘', hint: '幫助', mode: 'listening' },
    { word: 'hide', emoji: 'Ⓗ', hint: '隱藏', mode: 'spell' },
    { word: 'holiday', emoji: 'Ⓗ', hint: '假期', mode: 'spell' },
    { word: 'homework', emoji: 'Ⓗ', hint: '作業', mode: 'spell' },
    { word: 'hop', emoji: 'Ⓗ', hint: '跳', mode: 'spell' },
    { word: 'hospital', emoji: '🏥', hint: '醫院', mode: 'match' },
    { word: 'hot', emoji: '😅', hint: '熱', mode: 'listening' },
    { word: 'how', emoji: 'Ⓗ', hint: '怎樣（長）', mode: 'spell' },
    { word: 'how much', emoji: 'Ⓗ', hint: '多少', mode: 'spell' },
    { word: 'how often', emoji: 'Ⓗ', hint: '多久一次', mode: 'spell' },
    { word: 'huge', emoji: 'Ⓗ', hint: '巨大的', mode: 'spell' },
    { word: 'hundred', emoji: 'Ⓗ', hint: '一百', mode: 'spell' },
    { word: 'hungry', emoji: 'Ⓗ', hint: '餓了', mode: 'spell' },
    { word: 'hurt', emoji: 'Ⓗ', hint: '受傷', mode: 'spell' },
    { word: 'ice', emoji: '🥶', hint: '冰', mode: 'listening' },
    { word: 'ice skates', emoji: 'Ⓘ', hint: '溜冰鞋', mode: 'spell' },
    { word: 'ice skating', emoji: 'Ⓘ', hint: '滑冰', mode: 'spell' },
    { word: 'ill', emoji: '😷', hint: '生病了', mode: 'listening' },
    { word: 'internet', emoji: 'Ⓘ', hint: '網際網路', mode: 'spell' },
    { word: 'island', emoji: '🏝️', hint: '島', mode: 'listening' },
    { word: 'jungle', emoji: 'Ⓙ', hint: '叢林', mode: 'spell' },
    { word: 'kangaroo', emoji: '🦘', hint: '袋鼠', mode: 'match' },
    { word: 'kind', emoji: 'Ⓚ', hint: '善良', mode: 'spell' },
    { word: 'kitten', emoji: 'Ⓚ', hint: '小貓', mode: 'spell' },
    { word: 'lake', emoji: 'Ⓛ', hint: '湖', mode: 'spell' },
    { word: 'laptop', emoji: '💻', hint: '筆記型電腦', mode: 'match' },
    { word: 'last', emoji: '🌗', hint: '最後', mode: 'match' },
    { word: 'leaf', emoji: '🍃', hint: '葉', mode: 'match' },
    { word: 'library', emoji: '📚', hint: '圖書館', mode: 'listening' },
    { word: 'lift', emoji: 'Ⓛ', hint: '電梯', mode: 'spell' },
    { word: 'look for', emoji: '🔍', hint: '尋找', mode: 'match' },
    { word: 'lose', emoji: 'Ⓛ', hint: '失去', mode: 'spell' },
    { word: 'loud', emoji: 'Ⓛ', hint: '大聲', mode: 'spell' },
    { word: 'loudly', emoji: '😭', hint: '大聲地', mode: 'listening' },
    { word: 'machine', emoji: '🎰', hint: '機器', mode: 'listening' },
    { word: 'map', emoji: 'Ⓜ', hint: '地圖', mode: 'spell' },
    { word: 'market', emoji: 'Ⓜ', hint: '市場', mode: 'spell' },
    { word: 'matter', emoji: 'Ⓜ', hint: '事', mode: 'spell' },
    { word: 'mean', emoji: 'Ⓜ', hint: '意思是', mode: 'spell' },
    { word: 'message', emoji: 'Ⓜ', hint: '留言', mode: 'spell' },
    { word: 'milkshake', emoji: 'Ⓜ', hint: '奶昔', mode: 'spell' },
    { word: 'mistake', emoji: 'Ⓜ', hint: '錯誤', mode: 'spell' },
    { word: 'model', emoji: 'Ⓜ', hint: '模型', mode: 'spell' },
    { word: 'Monday', emoji: 'Ⓜ', hint: '星期一', mode: 'spell' },
    { word: 'moon', emoji: '🌔', hint: '月亮', mode: 'listening' },
    { word: 'more', emoji: 'Ⓜ', hint: '更多', mode: 'grammar', sentence: 'I need ___ time to finish my homework.', options: ['more', 'most', 'many', 'much'], correct: 'more', translation: '我需要更多時間來完成功課。' },
    { word: 'most', emoji: 'Ⓜ', hint: '大多數', mode: 'grammar', sentence: 'She is the ___ beautiful girl here.', options: ['most', 'more', 'much', 'very'], correct: 'most', translation: '她是這裡最美麗的女孩。' },
    { word: 'mountain', emoji: '⛰️', hint: '山', mode: 'listening' },
    { word: 'moustache', emoji: 'Ⓜ', hint: '小鬍子', mode: 'spell' },
    { word: 'move', emoji: 'Ⓜ', hint: '移動', mode: 'spell' },
    { word: 'must', emoji: 'Ⓜ', hint: '必須', mode: 'spell' },
    { word: 'naughty', emoji: 'Ⓝ', hint: '頑皮的', mode: 'spell' },
    { word: 'near', emoji: 'Ⓝ', hint: '附近', mode: 'grammar', sentence: 'My house is ___ the school.', options: ['near', 'far', 'opposite', 'under'], correct: 'near', translation: '我家在學校附近。' },
    { word: 'neck', emoji: 'Ⓝ', hint: '脖子', mode: 'spell' },
    { word: 'need', emoji: 'Ⓝ', hint: '需要', mode: 'spell' },
    { word: 'net', emoji: 'Ⓝ', hint: '網', mode: 'spell' },
    { word: 'never', emoji: 'Ⓝ', hint: '從不', mode: 'spell' },
    { word: 'nineteenth', emoji: 'Ⓝ', hint: '第十九號', mode: 'spell' },
    { word: 'ninety', emoji: 'Ⓝ', hint: '九十', mode: 'spell' },
    { word: 'ninth', emoji: 'Ⓝ', hint: '第九', mode: 'spell' },
    { word: 'noise', emoji: 'Ⓝ', hint: '噪音', mode: 'spell' },
    { word: 'noodles', emoji: '🍜', hint: '麵條', mode: 'match' },
    { word: 'nothing', emoji: 'Ⓝ', hint: '什麼都沒有', mode: 'grammar', sentence: 'There is ___ in the empty box.', options: ['nothing', 'something', 'anything', 'everything'], correct: 'nothing', translation: '空箱子裡什麼也沒有。' },
    { word: 'nurse', emoji: 'Ⓝ', hint: '護士', mode: 'spell' },
    { word: 'o\'clock', emoji: '🕛', hint: '點鐘', mode: 'match' },
    { word: 'off', emoji: '🔕', hint: '關閉', mode: 'grammar', sentence: 'Please turn ___ the light.', options: ['off', 'on', 'up', 'down'], correct: 'off', translation: '請關燈。' },
    { word: 'often', emoji: 'Ⓞ', hint: '常', mode: 'spell' },
    { word: 'only', emoji: 'Ⓞ', hint: '僅', mode: 'spell' },
    { word: 'opposite', emoji: 'Ⓞ', hint: '對面', mode: 'grammar', sentence: 'The library is ___ the park.', options: ['opposite', 'between', 'near', 'under'], correct: 'opposite', translation: '圖書館在公園對面。' },
    { word: 'out', emoji: 'Ⓞ', hint: '出', mode: 'spell' },
    { word: 'out of', emoji: 'Ⓞ', hint: '出於', mode: 'grammar', sentence: 'The cat jumped ___ the box.', options: ['out of', 'into', 'through', 'along'], correct: 'out of', translation: '貓從箱子裡跳了出來。' },
    { word: 'outside', emoji: 'Ⓞ', hint: '外面', mode: 'grammar', sentence: 'It is cold ___ the house.', options: ['outside', 'inside', 'downstairs', 'upstairs'], correct: 'outside', translation: '房子外面很冷。' },
    { word: 'pair', emoji: 'Ⓟ', hint: '一對', mode: 'spell' },
    { word: 'pancake', emoji: 'Ⓟ', hint: '煎餅', mode: 'spell' },
    { word: 'panda', emoji: '🐼', hint: '貓熊', mode: 'match' },
    { word: 'parent', emoji: 'Ⓟ', hint: '家長', mode: 'spell' },
    { word: 'parrot', emoji: '🦜', hint: '鸚鵡', mode: 'match' },
    { word: 'party', emoji: '🎂', hint: '聚會', mode: 'match' },
    { word: 'pasta', emoji: '🍝', hint: '義大利麵', mode: 'listening' },
    { word: 'penguin', emoji: '🐧', hint: '企鵝', mode: 'match' },
    { word: 'picnic', emoji: 'Ⓟ', hint: '野餐', mode: 'spell' },
    { word: 'pirate', emoji: '☠️', hint: '海盜', mode: 'listening' },
    { word: 'place', emoji: '🗺️', hint: '地方', mode: 'listening' },
    { word: 'plant', emoji: '🌱', hint: '植物', mode: 'listening' },
    { word: 'plate', emoji: '🍽️', hint: '盤子', mode: 'match' },
    { word: 'player', emoji: 'Ⓟ', hint: '玩家', mode: 'spell' },
    { word: 'pool', emoji: '🎱', hint: '泳池', mode: 'match' },
    { word: 'pop star', emoji: 'Ⓟ', hint: '流行歌星', mode: 'spell' },
    { word: 'practise', emoji: 'Ⓟ', hint: '練習', mode: 'spell' },
    { word: 'present', emoji: '🎁', hint: '現在', mode: 'listening' },
    { word: 'puppy', emoji: '🐶', hint: '小狗', mode: 'match' },
    { word: 'put on', emoji: 'Ⓟ', hint: '穿上', mode: 'spell' },
    { word: 'quick', emoji: 'Ⓠ', hint: '快', mode: 'spell' },
    { word: 'quickly', emoji: 'Ⓠ', hint: '快點', mode: 'spell' },
    { word: 'quiet', emoji: 'Ⓠ', hint: '安靜', mode: 'spell' },
    { word: 'quietly', emoji: 'Ⓠ', hint: '靜靜地', mode: 'spell' },
    { word: 'rain', emoji: '🌂', hint: '雨', mode: 'match' },
    { word: 'rainbow', emoji: '🌈', hint: '彩虹', mode: 'match' },
    { word: 'river', emoji: 'Ⓡ', hint: '河', mode: 'spell' },
    { word: 'road', emoji: 'Ⓡ', hint: '路', mode: 'spell' },
    { word: 'rock', emoji: '🪨', hint: '搖滾', mode: 'listening' },
    { word: 'roller skates', emoji: 'Ⓡ', hint: '旱冰鞋', mode: 'spell' },
    { word: 'roller skating', emoji: 'Ⓡ', hint: '輪滑', mode: 'spell' },
    { word: 'roof', emoji: 'Ⓡ', hint: '屋頂', mode: 'spell' },
    { word: 'round', emoji: '📍', hint: '圓形', mode: 'grammar', sentence: 'The wheels go ___ and round.', options: ['round', 'up', 'down', 'through'], correct: 'round', translation: '車輪轉啊轉。' },
    { word: 'safe', emoji: '🛡', hint: '安全', mode: 'listening' },
    { word: 'sail', emoji: 'Ⓢ', hint: '帆', mode: 'spell' },
    { word: 'salad', emoji: '🥗', hint: '沙拉', mode: 'listening' },
    { word: 'sandwich', emoji: '🥪', hint: '三明治', mode: 'listening' },
    { word: 'Saturday', emoji: '🏖', hint: '星期六', mode: 'listening' },
    { word: 'sauce', emoji: 'Ⓢ', hint: '醬汁', mode: 'spell' },
    { word: 'scarf', emoji: '🧣', hint: '圍巾', mode: 'listening' },
    { word: 'score', emoji: '💯', hint: '分數', mode: 'match' },
    { word: 'seat', emoji: '💺', hint: '座位', mode: 'listening' },
    { word: 'second', emoji: 'Ⓢ', hint: '第二', mode: 'spell' },
    { word: 'seventeenth', emoji: 'Ⓢ', hint: '第十七', mode: 'spell' },
    { word: 'seventh', emoji: 'Ⓢ', hint: '第七', mode: 'spell' },
    { word: 'seventy', emoji: 'Ⓢ', hint: '七十', mode: 'spell' },
    { word: 'shall', emoji: 'Ⓢ', hint: '應', mode: 'spell' },
    { word: 'shape', emoji: 'Ⓢ', hint: '形狀', mode: 'spell' },
    { word: 'shark', emoji: '🦈', hint: '鯊魚', mode: 'listening' },
    { word: 'shopping centre', emoji: 'Ⓢ', hint: '購物中心', mode: 'spell' },
    { word: 'shoulder', emoji: 'Ⓢ', hint: '肩膀', mode: 'spell' },
    { word: 'shout', emoji: '📢', hint: '喊', mode: 'listening' },
    { word: 'shower', emoji: '🚿', hint: '淋浴', mode: 'match' },
    { word: 'sick', emoji: 'Ⓢ', hint: '生病了', mode: 'spell' },
    { word: 'sixteenth', emoji: 'Ⓢ', hint: '第十六', mode: 'spell' },
    { word: 'sixth', emoji: 'Ⓢ', hint: '第六', mode: 'spell' },
    { word: 'sixty', emoji: 'Ⓢ', hint: '六十', mode: 'spell' },
    { word: 'skate', emoji: '🛼', hint: '滑冰', mode: 'match' },
    { word: 'skip', emoji: 'Ⓢ', hint: '跳過', mode: 'spell' },
    { word: 'slow', emoji: 'Ⓢ', hint: '慢', mode: 'spell' },
    { word: 'slowly', emoji: 'Ⓢ', hint: '慢慢地', mode: 'spell' },
    { word: 'snail', emoji: '🐌', hint: '蝸牛', mode: 'listening' },
    { word: 'snow', emoji: '🏔️', hint: '雪', mode: 'listening' },
    { word: 'someone', emoji: 'Ⓢ', hint: '某人', mode: 'grammar', sentence: '___ is knocking at the door.', options: ['Someone', 'Everyone', 'No one', 'Something'], correct: 'someone', translation: '有人正在敲門。' },
    { word: 'something', emoji: 'Ⓢ', hint: '某件事', mode: 'grammar', sentence: 'I want ___ sweet to eat.', options: ['something', 'nothing', 'anything', 'everything'], correct: 'something', translation: '我想吃點甜的東西。' },
    { word: 'sometimes', emoji: 'Ⓢ', hint: '有時', mode: 'spell' },
    { word: 'soup', emoji: 'Ⓢ', hint: '湯', mode: 'spell' },
    { word: 'sports centre', emoji: 'Ⓢ', hint: '體育中心', mode: 'spell' },
    { word: 'square', emoji: '🟥', hint: '方塊', mode: 'listening' },
    { word: 'stair', emoji: 'Ⓢ', hint: '樓梯', mode: 'spell' },
    { word: 'station', emoji: '🚉', hint: '車站', mode: 'match' },
    { word: 'stomach', emoji: 'Ⓢ', hint: '胃', mode: 'spell' },
    { word: 'stomach-ache', emoji: '🤢', hint: '胃痛', mode: 'listening' },
    { word: 'straight', emoji: '📏', hint: '直', mode: 'match' },
    { word: 'strong', emoji: '💪', hint: '強', mode: 'listening' },
    { word: 'Sunday', emoji: '📔', hint: '週日', mode: 'match' },
    { word: 'supermarket', emoji: 'Ⓢ', hint: '超市', mode: 'spell' },
    { word: 'surprised', emoji: 'Ⓢ', hint: '驚訝', mode: 'spell' },
    { word: 'sweater', emoji: 'Ⓢ', hint: '毛衣', mode: 'spell' },
    { word: 'sweet', emoji: '🍬', hint: '甜甜的', mode: 'match' },
    { word: 'swimming pool', emoji: 'Ⓢ', hint: '游泳池', mode: 'spell' },
    { word: 'swimsuit', emoji: '🩱', hint: '泳衣', mode: 'listening' },
    { word: 'take off', emoji: 'Ⓣ', hint: '脫掉（衣服）', mode: 'spell' },
    { word: 'tall', emoji: 'Ⓣ', hint: '高', mode: 'spell' },
    { word: 'tea', emoji: '🍵', hint: '茶', mode: 'match' },
    { word: 'teach', emoji: 'Ⓣ', hint: '教', mode: 'spell' },
    { word: 'temperature', emoji: 'Ⓣ', hint: '溫度', mode: 'spell' },
    { word: 'tenth', emoji: 'Ⓣ', hint: '第十', mode: 'spell' },
    { word: 'terrible', emoji: 'Ⓣ', hint: '可怕的', mode: 'spell' },
    { word: 'text', emoji: 'Ⓣ', hint: '文字', mode: 'spell' },
    { word: 'than', emoji: 'Ⓣ', hint: '比', mode: 'grammar', sentence: 'A horse is bigger ___ a sheep.', options: ['than', 'then', 'that', 'but'], correct: 'than', translation: '馬比羊大。' },
    { word: 'thin', emoji: 'Ⓣ', hint: '薄', mode: 'spell' },
    { word: 'think', emoji: 'Ⓣ', hint: '認為', mode: 'spell' },
    { word: 'third', emoji: 'Ⓣ', hint: '第三', mode: 'spell' },
    { word: 'thirsty', emoji: 'Ⓣ', hint: '渴了', mode: 'spell' },
    { word: 'thirteenth', emoji: 'Ⓣ', hint: '第十三', mode: 'spell' },
    { word: 'thirty', emoji: '🕧', hint: '三十', mode: 'match' },
    { word: 'Thursday', emoji: 'Ⓣ', hint: '星期四', mode: 'spell' },
    { word: 'ticket', emoji: '🎫', hint: '票', mode: 'match' },
    { word: 'tired', emoji: '😪', hint: '累了', mode: 'match' },
    { word: 'tooth', emoji: '🦷', hint: '牙齒', mode: 'match' },
    { word: 'toothache', emoji: '🤕', hint: '牙痛', mode: 'listening' },
    { word: 'toothbrush', emoji: '🪥', hint: '牙刷', mode: 'match' },
    { word: 'toothpaste', emoji: '🪥', hint: '牙膏', mode: 'listening' },
    { word: 'top', emoji: '🔝', hint: '頂部', mode: 'listening' },
    { word: 'towel', emoji: '🧽', hint: '毛巾', mode: 'listening' },
    { word: 'town', emoji: 'Ⓣ', hint: '鎮', mode: 'spell' },
    { word: 'town center', emoji: 'Ⓣ', hint: '市中心', mode: 'spell' },
    { word: 'tractor', emoji: '🚜', hint: '聯結機', mode: 'listening' },
    { word: 'travel', emoji: '🗺️', hint: '旅行', mode: 'match' },
    { word: 'treasure', emoji: 'Ⓣ', hint: '寶藏', mode: 'spell' },
    { word: 'trip', emoji: 'Ⓣ', hint: '旅行', mode: 'spell' },
    { word: 'Tuesday', emoji: 'Ⓣ', hint: '星期二', mode: 'spell' },
    { word: 'twelfth', emoji: 'Ⓣ', hint: '第十二', mode: 'spell' },
    { word: 'twentieth', emoji: 'Ⓣ', hint: '第二十', mode: 'spell' },
    { word: 'uncle', emoji: 'Ⓤ', hint: '叔叔', mode: 'spell' },
    { word: 'up', emoji: '🆙', hint: '向上', mode: 'grammar', sentence: 'Look ___ at the blue sky.', options: ['up', 'down', 'through', 'into'], correct: 'up', translation: '抬頭看著藍天。' },
    { word: 'upstairs', emoji: 'Ⓤ', hint: '樓上', mode: 'grammar', sentence: 'My bedroom is ___.', options: ['upstairs', 'downstairs', 'outside', 'inside'], correct: 'upstairs', translation: '我的臥室在樓上。' },
    { word: 'vegetable', emoji: 'Ⓥ', hint: '蔬菜', mode: 'spell' },
    { word: 'video', emoji: '🎮', hint: '影片', mode: 'listening' },
    { word: 'wait', emoji: 'Ⓦ', hint: '等待', mode: 'spell' },
    { word: 'wake up', emoji: '⏰', hint: '醒來', mode: 'listening' },
    { word: 'wash', emoji: 'Ⓦ', hint: '洗', mode: 'spell' },
    { word: 'waterfall', emoji: 'Ⓦ', hint: '瀑布', mode: 'spell' },
    { word: 'wave', emoji: '👋', hint: '波', mode: 'listening' },
    { word: 'weak', emoji: 'Ⓦ', hint: '弱', mode: 'spell' },
    { word: 'website', emoji: 'Ⓦ', hint: '網站', mode: 'spell' },
    { word: 'Wednesday', emoji: 'Ⓦ', hint: '星期三', mode: 'spell' },
    { word: 'week', emoji: 'Ⓦ', hint: '週', mode: 'spell' },
    { word: 'weekend', emoji: '🏖', hint: '週末', mode: 'listening' },
    { word: 'well', emoji: 'Ⓦ', hint: '好（做得好／感覺好）', mode: 'spell' },
    { word: 'wet', emoji: 'Ⓦ', hint: '濕的', mode: 'spell' },
    { word: 'whale', emoji: '🐳', hint: '鯨魚', mode: 'listening' },
    { word: 'when', emoji: 'Ⓦ', hint: '當', mode: 'grammar', sentence: 'I will call you ___ I arrive.', options: ['when', 'why', 'where', 'who'], correct: 'when', translation: '我到了之後會打電話給你。' },
    { word: 'where', emoji: 'Ⓦ', hint: '其中 (a ... b)', mode: 'grammar', sentence: 'This is the park ___ we play football.', options: ['where', 'who', 'which', 'whose'], correct: 'where', translation: '這就是我們踢足球的公園。' },
    { word: 'which', emoji: 'Ⓦ', hint: '其中（a ... b）', mode: 'grammar', sentence: 'The book ___ I read yesterday was good.', options: ['which', 'who', 'where', 'whose'], correct: 'which', translation: '我昨天讀的那本書很好。' },
    { word: 'who', emoji: 'Ⓦ', hint: '誰（a ... b）', mode: 'grammar', sentence: 'This is the doctor ___ helped me.', options: ['who', 'which', 'where', 'whose'], correct: 'who', translation: '這就是幫助過我的醫生。' },
    { word: 'wind', emoji: '💨', hint: '風', mode: 'match' },
    { word: 'windy', emoji: 'Ⓦ', hint: '有風的', mode: 'spell' },
    { word: 'work', emoji: 'Ⓦ', hint: '工作', mode: 'spell' },
    { word: 'world', emoji: '🌍', hint: '世界', mode: 'match' },
    { word: 'worse', emoji: 'Ⓦ', hint: '更糟', mode: 'spell' },
    { word: 'worst', emoji: 'Ⓦ', hint: '最糟糕的', mode: 'spell' },
    { word: 'would', emoji: 'Ⓦ', hint: '會', mode: 'spell' },
    { word: 'wrong', emoji: 'Ⓦ', hint: '錯誤的', mode: 'spell' },
    { word: 'yesterday', emoji: 'Ⓨ', hint: '昨天', mode: 'spell' },
    { word: 'ask', emoji: 'Ⓐ', hint: '問', mode: 'spell' },
    { word: 'basketball', emoji: '🏀', hint: '籃球', mode: 'listening' },
    { word: 'beach', emoji: '🐚', hint: '海灘', mode: 'listening' },
    { word: 'between', emoji: 'Ⓑ', hint: '之間', mode: 'grammar', sentence: 'The ball is ___ the two boxes.', options: ['between', 'under', 'in', 'next to'], correct: 'between', translation: '球在兩個箱子之間。' },
    { word: 'bookshop', emoji: 'Ⓑ', hint: '書店', mode: 'spell' },
    { word: 'camera', emoji: '📷', hint: '相機', mode: 'listening' },
    { word: 'choose', emoji: '☑', hint: '選擇', mode: 'listening' },
    { word: 'count', emoji: 'Ⓒ', hint: '計數', mode: 'spell' },
    { word: 'cross', emoji: '❌', hint: '打叉', mode: 'match' },
    { word: 'enjoy', emoji: 'Ⓔ', hint: '享受', mode: 'spell' },
    { word: 'great', emoji: 'Ⓖ', hint: '太棒了', mode: 'spell' },
    { word: 'learn', emoji: 'Ⓛ', hint: '學習', mode: 'spell' },
    { word: 'lesson', emoji: 'Ⓛ', hint: '課程', mode: 'spell' },
    { word: 'line', emoji: '🫥', hint: '線', mode: 'match' },
    { word: 'live', emoji: 'Ⓛ', hint: '居住', mode: 'spell' },
    { word: 'arrive', emoji: 'Ⓐ', hint: '到達', mode: 'spell' },
    { word: 'bored', emoji: 'Ⓑ', hint: '無聊', mode: 'spell' },
    { word: 'butter', emoji: '🧈', hint: '奶油', mode: 'match' },
    { word: 'butterfly', emoji: '🦋', hint: '蝴蝶', mode: 'listening' },
    { word: 'calendar', emoji: '📆', hint: '日曆', mode: 'match' },
    { word: 'camel', emoji: '🐫', hint: '駱駝', mode: 'match' },
    { word: 'camp', emoji: 'Ⓒ', hint: '營地', mode: 'spell' },
    { word: 'chess', emoji: '♟️', hint: '西洋棋', mode: 'match' },
    { word: 'collect', emoji: 'Ⓒ', hint: '收集', mode: 'spell' },
    { word: 'competition', emoji: 'Ⓒ', hint: '競爭', mode: 'spell' },
    { word: 'corner', emoji: 'Ⓒ', hint: '角落', mode: 'spell' },
    { word: 'decide', emoji: 'Ⓓ', hint: '決定', mode: 'spell' },
    { word: 'diary', emoji: 'Ⓓ', hint: '日記', mode: 'spell' },
    { word: 'drum', emoji: '🥁', hint: '鼓', mode: 'match' },
    { word: 'during', emoji: 'Ⓓ', hint: '期間', mode: 'grammar', sentence: 'We stayed silent ___ the test.', options: ['during', 'for', 'since', 'while'], correct: 'during', translation: '考試期間我們保持安靜。' },
    { word: 'each', emoji: 'Ⓔ', hint: '每個', mode: 'grammar', sentence: '___ student gets a prize.', options: ['Each', 'All', 'Every', 'Both'], correct: 'each', translation: '每個學生都得到一份獎品。' },
    { word: 'early', emoji: 'Ⓔ', hint: '早', mode: 'spell' },
    { word: 'enough', emoji: 'Ⓔ', hint: '夠了', mode: 'grammar', sentence: 'I don\'t have ___ money to buy this.', options: ['enough', 'many', 'much', 'more'], correct: 'enough', translation: '我沒有足夠的錢買這個。' },
    { word: 'enter', emoji: 'Ⓔ', hint: '參加（比賽）', mode: 'spell' },
    { word: 'envelope', emoji: '✉️', hint: '信封', mode: 'match' },
    { word: 'explain', emoji: 'Ⓔ', hint: '解釋一下', mode: 'spell' },
    { word: 'far', emoji: 'Ⓕ', hint: '遠', mode: 'spell' },
    { word: 'feel', emoji: 'Ⓕ', hint: '感覺', mode: 'spell' },
    { word: 'follow', emoji: 'Ⓕ', hint: '關注', mode: 'spell' },
    { word: 'forget', emoji: 'Ⓕ', hint: '忘記', mode: 'spell' },
    { word: 'geography', emoji: 'Ⓖ', hint: '地理', mode: 'spell' },
    { word: 'glove', emoji: '🧤', hint: '手套', mode: 'listening' },
    { word: 'gold', emoji: '🏅', hint: '黃金', mode: 'match' },
    { word: 'guess', emoji: 'Ⓖ', hint: '猜測', mode: 'spell' },
    { word: 'gym', emoji: '🏋️', hint: '健身房', mode: 'listening' },
    { word: 'history', emoji: 'Ⓗ', hint: '歷史', mode: 'spell' },
    { word: 'hotel', emoji: '🏨', hint: '飯店', mode: 'match' },
    { word: 'hour', emoji: 'Ⓗ', hint: '小時', mode: 'spell' },
    { word: 'hurry', emoji: 'Ⓗ', hint: '快點', mode: 'spell' },
    { word: 'if', emoji: 'Ⓘ', hint: '如果', mode: 'grammar', sentence: '___ you study hard, you will pass.', options: ['If', 'Unless', 'Although', 'Because'], correct: 'if', translation: '如果你努力學習，你就會通過。' },
    { word: 'important', emoji: 'Ⓘ', hint: '重要的', mode: 'spell' },
    { word: 'job', emoji: 'Ⓙ', hint: '工作', mode: 'spell' },
    { word: 'journey', emoji: 'Ⓙ', hint: '旅程', mode: 'spell' },
    { word: 'keep', emoji: 'Ⓚ', hint: '保留', mode: 'spell' },
    { word: 'key', emoji: '🔑', hint: '鑰匙', mode: 'listening' },
    { word: 'lazy', emoji: 'Ⓛ', hint: '懶惰', mode: 'spell' },
    { word: 'leave', emoji: 'Ⓛ', hint: '離開', mode: 'spell' },
    { word: 'lucky', emoji: 'Ⓛ', hint: '幸運的', mode: 'spell' },
    { word: 'magazine', emoji: 'Ⓜ', hint: '雜誌', mode: 'spell' },
    { word: 'meal', emoji: 'Ⓜ', hint: '餐', mode: 'spell' },
    { word: 'meet', emoji: 'Ⓜ', hint: '見面', mode: 'spell' },
    { word: 'member', emoji: 'Ⓜ', hint: '會員', mode: 'spell' },
    { word: 'missing', emoji: 'Ⓜ', hint: '失蹤', mode: 'spell' },
    { word: 'month', emoji: 'Ⓜ', hint: '月', mode: 'spell' },
    { word: 'museum', emoji: '🏛', hint: '博物館', mode: 'match' },
    { word: 'touch', emoji: 'Ⓣ', hint: '觸摸', mode: 'spell' },
    { word: 'traffic', emoji: '🚥', hint: '交通', mode: 'listening' },
    { word: 'uniform', emoji: '🥋', hint: '制服', mode: 'match' }
  ],
  flyers: [
    { word: 'a few', emoji: 'Ⓐ', hint: '一些', mode: 'grammar', sentence: 'I have ___ cookies in my pocket.', options: ['a few', 'a little', 'much', 'any'], correct: 'a few', translation: '我口袋裡有幾片餅乾。' },
    { word: 'a little', emoji: 'Ⓐ', hint: '一點', mode: 'grammar', sentence: 'Could I have ___ sugar in my tea?', options: ['a little', 'a few', 'many', 'any'], correct: 'a little', translation: '我的茶裡可以加一點糖嗎？' },
    { word: 'a.m.', emoji: 'Ⓐ', hint: '上午', mode: 'spell' },
    { word: 'across', emoji: 'Ⓐ', hint: '跨越', mode: 'grammar', sentence: 'We walked ___ the bridge.', options: ['across', 'along', 'through', 'into'], correct: 'across', translation: '我們走過橋。' },
    { word: 'act', emoji: 'Ⓐ', hint: '行動', mode: 'spell' },
    { word: 'actor', emoji: 'Ⓐ', hint: '演員', mode: 'spell' },
    { word: 'actually', emoji: 'Ⓐ', hint: '實際上', mode: 'spell' },
    { word: 'adventure', emoji: 'Ⓐ', hint: '冒險', mode: 'spell' },
    { word: 'ago', emoji: 'Ⓐ', hint: '前', mode: 'spell' },
    { word: 'agree', emoji: 'Ⓐ', hint: '同意', mode: 'spell' },
    { word: 'air', emoji: 'Ⓐ', hint: '空氣', mode: 'spell' },
    { word: 'airport', emoji: '🛄', hint: '機場', mode: 'listening' },
    { word: 'alone', emoji: 'Ⓐ', hint: '獨自一人', mode: 'spell' },
    { word: 'already', emoji: 'Ⓐ', hint: '已經', mode: 'spell' },
    { word: 'also', emoji: '➕', hint: '還有', mode: 'listening' },
    { word: 'amazing', emoji: 'Ⓐ', hint: '驚人的', mode: 'spell' },
    { word: 'ambulance', emoji: '🚑', hint: '救護車', mode: 'match' },
    { word: 'anyone', emoji: 'Ⓐ', hint: '任何人', mode: 'grammar', sentence: 'Is ___ here?', options: ['anyone', 'someone', 'everyone', 'no-one'], correct: 'anyone', translation: '有人在這裡嗎？' },
    { word: 'anything', emoji: 'Ⓐ', hint: '任何東西', mode: 'grammar', sentence: 'Do you want ___ to drink?', options: ['anything', 'something', 'nothing', 'everything'], correct: 'anything', translation: '你想要喝點什麼嗎？' },
    { word: 'anywhere', emoji: 'Ⓐ', hint: '任何地方', mode: 'spell' },
    { word: 'appear', emoji: 'Ⓐ', hint: '出現', mode: 'spell' },
    { word: 'April', emoji: 'Ⓐ', hint: '四月', mode: 'spell' },
    { word: 'art', emoji: '🎨', hint: '藝術', mode: 'listening' },
    { word: 'artist', emoji: '🧑‍🎨', hint: '藝術家', mode: 'listening' },
    { word: 'as', emoji: 'Ⓐ', hint: '作為', mode: 'spell' },
    { word: 'as ... as', emoji: 'Ⓐ', hint: '作為...作為', mode: 'spell' },
    { word: 'astronaut', emoji: '🧑‍🚀', hint: '太空人', mode: 'listening' },
    { word: 'at the moment', emoji: 'Ⓐ', hint: '此刻', mode: 'spell' },
    { word: 'August', emoji: 'Ⓐ', hint: '八月', mode: 'spell' },
    { word: 'autumn', emoji: '🍂', hint: '秋天', mode: 'match' },
    { word: 'away', emoji: '💨', hint: '離開', mode: 'match' },
    { word: 'bandage', emoji: '🤕', hint: '繃帶', mode: 'match' },
    { word: 'bank', emoji: '🏦', hint: '銀行', mode: 'match' },
    { word: 'beetle', emoji: '🪲', hint: '甲蟲', mode: 'listening' },
    { word: 'begin', emoji: 'Ⓑ', hint: '開始', mode: 'spell' },
    { word: 'believe', emoji: 'Ⓑ', hint: '相信', mode: 'spell' },
    { word: 'belt', emoji: 'Ⓑ', hint: '腰帶', mode: 'spell' },
    { word: 'bicycle', emoji: '🚲', hint: '自行車', mode: 'listening' },
    { word: 'bin', emoji: 'Ⓑ', hint: '垃圾桶', mode: 'spell' },
    { word: 'biscuit', emoji: 'Ⓑ', hint: '餅乾', mode: 'spell' },
    { word: 'bit', emoji: 'Ⓑ', hint: '一點', mode: 'spell' },
    { word: 'borrow', emoji: 'Ⓑ', hint: '借', mode: 'spell' },
    { word: 'bracelet', emoji: 'Ⓑ', hint: '手鐲', mode: 'spell' },
    { word: 'break', emoji: 'Ⓑ', hint: '打破', mode: 'spell' },
    { word: 'bridge', emoji: '🌉', hint: '橋', mode: 'listening' },
    { word: 'broken', emoji: '💔', hint: '壞了', mode: 'listening' },
    { word: 'brush', emoji: 'Ⓑ', hint: '刷子', mode: 'spell' },
    { word: 'burn', emoji: '🔥', hint: '燒傷', mode: 'listening' },
    { word: 'business', emoji: '👨‍💼', hint: '商業', mode: 'match' },
    { word: 'businessman', emoji: 'Ⓑ', hint: '商人', mode: 'spell' },
    { word: 'businesswoman', emoji: 'Ⓑ', hint: '女商人', mode: 'spell' },
    { word: 'by myself', emoji: 'Ⓑ', hint: '我自己', mode: 'spell' },
    { word: 'by yourself', emoji: 'Ⓑ', hint: '自己', mode: 'spell' },
    { word: 'card', emoji: '🃏', hint: '卡', mode: 'match' },
    { word: 'cartoon', emoji: 'Ⓒ', hint: '卡通', mode: 'spell' },
    { word: 'castle', emoji: '🏯', hint: '城堡', mode: 'match' },
    { word: 'cave', emoji: 'Ⓒ', hint: '洞穴', mode: 'spell' },
    { word: 'century', emoji: 'Ⓒ', hint: '世紀', mode: 'spell' },
    { word: 'cereal', emoji: 'Ⓒ', hint: '穀物', mode: 'spell' },
    { word: 'channel', emoji: 'Ⓒ', hint: '頻道', mode: 'spell' },
    { word: 'chat', emoji: 'Ⓒ', hint: '聊天', mode: 'spell' },
    { word: 'cheap', emoji: 'Ⓒ', hint: '便宜', mode: 'spell' },
    { word: 'chemist', emoji: 'Ⓒ', hint: '化學家', mode: 'spell' },
    { word: 'chopsticks', emoji: '🥢', hint: '筷子', mode: 'listening' },
    { word: 'club', emoji: 'Ⓒ', hint: '俱樂部', mode: 'spell' },
    { word: 'college', emoji: '🎓', hint: '學院', mode: 'listening' },
    { word: 'comb', emoji: '🪮', hint: '梳子', mode: 'listening' },
    { word: 'concert', emoji: 'Ⓒ', hint: '音樂會', mode: 'spell' },
    { word: 'conversation', emoji: 'Ⓒ', hint: '談話', mode: 'spell' },
    { word: 'cooker', emoji: '🍳', hint: '炊具', mode: 'listening' },
    { word: 'costume', emoji: 'Ⓒ', hint: '服裝', mode: 'spell' },
    { word: 'could', emoji: 'Ⓒ', hint: '可以（可能性）', mode: 'spell' },
    { word: 'creature', emoji: 'Ⓒ', hint: '生物', mode: 'spell' },
    { word: 'crown', emoji: '👑', hint: '皇冠', mode: 'listening' },
    { word: 'cushion', emoji: 'Ⓒ', hint: '坐墊', mode: 'spell' },
    { word: 'cut', emoji: '🔪', hint: '切', mode: 'match' },
    { word: 'cycle', emoji: '🚲', hint: '循環', mode: 'match' },
    { word: 'dark', emoji: 'Ⓓ', hint: '黑暗', mode: 'spell' },
    { word: 'date', emoji: '📅', hint: '日期（時間）', mode: 'match' },
    { word: 'dear', emoji: 'Ⓓ', hint: '親愛的', mode: 'spell' },
    { word: 'December', emoji: 'Ⓓ', hint: '十二月', mode: 'spell' },
    { word: 'deep', emoji: 'Ⓓ', hint: '深', mode: 'spell' },
    { word: 'delicious', emoji: 'Ⓓ', hint: '好吃', mode: 'spell' },
    { word: 'desert', emoji: '🏜️', hint: '沙漠', mode: 'listening' },
    { word: 'design', emoji: 'Ⓓ', hint: '設計', mode: 'spell' },
    { word: 'designer', emoji: 'Ⓓ', hint: '設計師', mode: 'spell' },
    { word: 'dictionary', emoji: '📖', hint: '字典', mode: 'match' },
    { word: 'dinosaur', emoji: '🦕', hint: '恐龍', mode: 'listening' },
    { word: 'disappear', emoji: 'Ⓓ', hint: '消失', mode: 'spell' },
    { word: 'eagle', emoji: '🦅', hint: '鷹', mode: 'match' },
    { word: 'Earth', emoji: 'Ⓔ', hint: '地球', mode: 'spell' },
    { word: 'east', emoji: 'Ⓔ', hint: '東', mode: 'grammar', sentence: 'The sun rises in the ___.', options: ['east', 'west', 'north', 'south'], correct: 'east', translation: '太陽從東方升起。' },
    { word: 'eight hundred', emoji: 'Ⓔ', hint: '八百', mode: 'spell' },
    { word: 'elbow', emoji: '💪', hint: '手肘', mode: 'listening' },
    { word: 'else', emoji: 'Ⓔ', hint: '否則', mode: 'spell' },
    { word: 'empty', emoji: '🪹', hint: '空的', mode: 'listening' },
    { word: 'engine', emoji: '🚒', hint: '引擎', mode: 'match' },
    { word: 'engineer', emoji: '👷', hint: '工程師', mode: 'listening' },
    { word: 'enormous', emoji: 'Ⓔ', hint: '巨大的', mode: 'spell' },
    { word: 'entrance', emoji: 'Ⓔ', hint: '入口', mode: 'spell' },
    { word: 'environment', emoji: '♻️', hint: '環境', mode: 'listening' },
    { word: 'ever', emoji: 'Ⓔ', hint: '曾經', mode: 'spell' },
    { word: 'everywhere', emoji: 'Ⓔ', hint: '到處', mode: 'spell' },
    { word: 'excellent', emoji: 'Ⓔ', hint: '優秀的', mode: 'spell' },
    { word: 'excited', emoji: 'Ⓔ', hint: '興奮', mode: 'spell' },
    { word: 'exit', emoji: 'Ⓔ', hint: '退出', mode: 'spell' },
    { word: 'expensive', emoji: 'Ⓔ', hint: '昂貴', mode: 'spell' },
    { word: 'explore', emoji: 'Ⓔ', hint: '探索', mode: 'spell' },
    { word: 'extinct', emoji: 'Ⓔ', hint: '滅絕的', mode: 'spell' },
    { word: 'factory', emoji: '🏭', hint: '工廠', mode: 'match' },
    { word: 'fall over', emoji: 'Ⓕ', hint: '跌倒', mode: 'spell' },
    { word: 'fast', emoji: 'Ⓕ', hint: '快', mode: 'spell' },
    { word: 'February', emoji: 'Ⓕ', hint: '二月', mode: 'spell' },
    { word: 'festival', emoji: '🎆', hint: '節慶', mode: 'match' },
    { word: 'fetch', emoji: 'Ⓕ', hint: '獲取', mode: 'spell' },
    { word: 'file', emoji: '📁', hint: '文件（打開一個）', mode: 'match' },
    { word: 'find out', emoji: 'Ⓕ', hint: '找出來', mode: 'spell' },
    { word: 'finger', emoji: '🫰', hint: '手指', mode: 'listening' },
    { word: 'finish', emoji: 'Ⓕ', hint: '完成', mode: 'spell' },
    { word: 'fire', emoji: '🔥', hint: '火', mode: 'match' },
    { word: 'fire engine', emoji: '🚒', hint: '消防車', mode: 'match' },
    { word: 'fire fighter', emoji: '🚒', hint: '消防員', mode: 'listening' },
    { word: 'fire station', emoji: '🚒', hint: '消防局', mode: 'match' },
    { word: 'five hundred', emoji: 'Ⓕ', hint: '五百', mode: 'spell' },
    { word: 'flag', emoji: '🚩', hint: '旗幟', mode: 'match' },
    { word: 'flour', emoji: 'Ⓕ', hint: '麵粉', mode: 'spell' },
    { word: 'fog', emoji: '🌫️', hint: '霧', mode: 'match' },
    { word: 'foggy', emoji: '🌁', hint: '有霧的', mode: 'match' },
    { word: 'for', emoji: 'Ⓕ', hint: '（一小時）', mode: 'grammar', sentence: 'This gift is ___ you.', options: ['for', 'to', 'at', 'with'], correct: 'for', translation: '這個禮物是給你的。' },
    { word: 'fork', emoji: '🍽️', hint: '叉子', mode: 'match' },
    { word: 'four hundred', emoji: 'Ⓕ', hint: '四百', mode: 'spell' },
    { word: 'fridge', emoji: 'Ⓕ', hint: '冰箱', mode: 'spell' },
    { word: 'friendly', emoji: 'Ⓕ', hint: '友善的', mode: 'spell' },
    { word: 'frightening', emoji: 'Ⓕ', hint: '令人恐懼的', mode: 'spell' },
    { word: 'front', emoji: 'Ⓕ', hint: '前面', mode: 'grammar', sentence: 'Please sit in the ___ row.', options: ['front', 'back', 'middle', 'left'], correct: 'front', translation: '請坐在前排。' },
    { word: 'full', emoji: '🌕', hint: '滿', mode: 'listening' },
    { word: 'fur', emoji: 'Ⓕ', hint: '皮草', mode: 'spell' },
    { word: 'furry', emoji: 'Ⓕ', hint: '毛茸茸的', mode: 'spell' },
    { word: 'future', emoji: 'Ⓕ', hint: '未來', mode: 'spell' },
    { word: 'gate', emoji: 'Ⓖ', hint: '門', mode: 'spell' },
    { word: 'get to', emoji: 'Ⓖ', hint: '到達', mode: 'spell' },
    { word: 'glass', emoji: '🥛', hint: '玻璃（窗格）', mode: 'match' },
    { word: 'glue', emoji: '🧴', hint: '膠水', mode: 'listening' },
    { word: 'go out', emoji: 'Ⓖ', hint: '出去', mode: 'spell' },
    { word: 'golf', emoji: '⛳', hint: '高爾夫', mode: 'match' },
    { word: 'group', emoji: 'Ⓖ', hint: '群組', mode: 'spell' },
    { word: 'half', emoji: 'Ⓗ', hint: '一半', mode: 'spell' },
    { word: 'happen', emoji: 'Ⓗ', hint: '發生', mode: 'spell' },
    { word: 'hate', emoji: 'Ⓗ', hint: '討厭', mode: 'spell' },
    { word: 'hear', emoji: '👂', hint: '聽到', mode: 'match' },
    { word: 'heavy', emoji: '🟰', hint: '重', mode: 'listening' },
    { word: 'high', emoji: '🚄', hint: '高', mode: 'match' },
    { word: 'hill', emoji: 'Ⓗ', hint: '山', mode: 'spell' },
    { word: 'hole', emoji: '🕳️', hint: '洞', mode: 'match' },
    { word: 'honey', emoji: '🍯', hint: '蜂蜜', mode: 'listening' },
    { word: 'hope', emoji: 'Ⓗ', hint: '希望', mode: 'spell' },
    { word: 'horrible', emoji: 'Ⓗ', hint: '可怕的', mode: 'spell' },
    { word: 'how long', emoji: 'Ⓗ', hint: '多長時間', mode: 'spell' },
    { word: 'husband', emoji: 'Ⓗ', hint: '丈夫', mode: 'spell' },
    { word: 'improve', emoji: 'Ⓘ', hint: '改善', mode: 'spell' },
    { word: 'information', emoji: '💁‍♂️', hint: '資訊', mode: 'match' },
    { word: 'insect', emoji: '🐛', hint: '昆蟲', mode: 'match' },
    { word: 'instead', emoji: 'Ⓘ', hint: '相反', mode: 'spell' },
    { word: 'instrument', emoji: 'Ⓘ', hint: '儀器', mode: 'spell' },
    { word: 'interested', emoji: 'Ⓘ', hint: '有興趣', mode: 'spell' },
    { word: 'interesting', emoji: 'Ⓘ', hint: '有趣的', mode: 'spell' },
    { word: 'invent', emoji: 'Ⓘ', hint: '發明', mode: 'spell' },
    { word: 'invitation', emoji: 'Ⓘ', hint: '邀請函', mode: 'spell' },
    { word: 'jam', emoji: 'Ⓙ', hint: '果醬', mode: 'spell' },
    { word: 'January', emoji: 'Ⓙ', hint: '一月', mode: 'spell' },
    { word: 'join', emoji: 'Ⓙ', hint: '加入（俱樂部）', mode: 'spell' },
    { word: 'journalist', emoji: 'Ⓙ', hint: '記者', mode: 'spell' },
    { word: 'July', emoji: 'Ⓙ', hint: '七月', mode: 'spell' },
    { word: 'June', emoji: 'Ⓙ', hint: '六月', mode: 'spell' },
    { word: 'kilometre', emoji: 'Ⓚ', hint: '公里', mode: 'spell' },
    { word: 'king', emoji: 'Ⓚ', hint: '國王', mode: 'spell' },
    { word: 'knee', emoji: 'Ⓚ', hint: '膝蓋', mode: 'spell' },
    { word: 'knife', emoji: '🔪', hint: '刀', mode: 'listening' },
    { word: 'land', emoji: 'Ⓛ', hint: '土地', mode: 'spell' },
    { word: 'language', emoji: 'Ⓛ', hint: '語言', mode: 'spell' },
    { word: 'large', emoji: '🌥️', hint: '大', mode: 'listening' },
    { word: 'late', emoji: 'Ⓛ', hint: '遲到了', mode: 'spell' },
    { word: 'later', emoji: 'Ⓛ', hint: '後來', mode: 'spell' },
    { word: 'left', emoji: '🗨️', hint: '左（方向）', mode: 'grammar', sentence: 'Turn ___ at the corner.', options: ['left', 'right', 'straight', 'forward'], correct: 'left', translation: '在轉角處左轉。' },
    { word: 'let', emoji: 'Ⓛ', hint: '讓', mode: 'spell' },
    { word: 'letter', emoji: '✉️', hint: '信件（郵件）', mode: 'match' },
    { word: 'lie', emoji: 'Ⓛ', hint: '躺著（躺下）', mode: 'spell' },
    { word: 'lift', emoji: '🛗', hint: '舉起／電梯', mode: 'match' },
    { word: 'light', emoji: '💡', hint: '光', mode: 'match' },
    { word: 'London', emoji: 'Ⓛ', hint: '倫敦', mode: 'spell' },
    { word: 'look after', emoji: '💖', hint: '照顧', mode: 'listening' },
    { word: 'look like', emoji: 'Ⓛ', hint: '看起來像', mode: 'spell' },
    { word: 'lovely', emoji: 'Ⓛ', hint: '可愛的', mode: 'spell' },
    { word: 'low', emoji: 'Ⓛ', hint: '低', mode: 'spell' },
    { word: 'make sure', emoji: 'Ⓜ', hint: '確保', mode: 'spell' },
    { word: 'manager', emoji: 'Ⓜ', hint: '主管', mode: 'spell' },
    { word: 'March', emoji: 'Ⓜ', hint: '三月', mode: 'spell' },
    { word: 'married', emoji: 'Ⓜ', hint: '已婚', mode: 'spell' },
    { word: 'match', emoji: 'Ⓜ', hint: '比賽（足球）', mode: 'spell' },
    { word: 'maths', emoji: '📐', hint: '數學', mode: 'listening' },
    { word: 'May', emoji: 'Ⓜ', hint: '五月（月）', mode: 'spell' },
    { word: 'may', emoji: 'Ⓜ', hint: '可能', mode: 'spell' },
    { word: 'mechanic', emoji: '🧑‍🔧', hint: '機械師', mode: 'match' },
    { word: 'medicine', emoji: '💊', hint: '醫學', mode: 'match' },
    { word: 'meeting', emoji: 'Ⓜ', hint: '會議', mode: 'spell' },
    { word: 'metal', emoji: '🤘', hint: '金屬', mode: 'listening' },
    { word: 'midday', emoji: '🌅', hint: '中午', mode: 'match' },
    { word: 'middle', emoji: '⬛', hint: '中', mode: 'grammar', sentence: 'There is a fountain in the ___ of the park.', options: ['middle', 'front', 'back', 'left'], correct: 'middle', translation: '公園中央有一個噴水池。' },
    { word: 'midnight', emoji: '🌃', hint: '午夜', mode: 'match' },
    { word: 'might', emoji: 'Ⓜ', hint: '可能', mode: 'spell' },
    { word: 'million', emoji: 'Ⓜ', hint: '百萬', mode: 'spell' },
    { word: 'mind', emoji: '🤯', hint: '頭腦', mode: 'match' },
    { word: 'minute', emoji: 'Ⓜ', hint: '分分鐘', mode: 'spell' },
    { word: 'mix', emoji: 'Ⓜ', hint: '混合', mode: 'spell' },
    { word: 'money', emoji: '💵', hint: '錢', mode: 'match' },
    { word: 'motorway', emoji: '🛣️', hint: '高速公路', mode: 'match' },
    { word: 'much', emoji: 'Ⓜ', hint: '很多', mode: 'spell' },
    { word: 'necklace', emoji: '📿', hint: '項鍊', mode: 'match' },
    { word: 'nest', emoji: '🪺', hint: '巢', mode: 'match' },
    { word: 'news', emoji: '🆕', hint: '新聞', mode: 'listening' },
    { word: 'newspaper', emoji: '📰', hint: '報紙', mode: 'listening' },
    { word: 'next', emoji: '⏭️', hint: '下一個', mode: 'listening' },
    { word: 'nine hundred', emoji: 'Ⓝ', hint: '九百', mode: 'spell' },
    { word: 'noisy', emoji: 'Ⓝ', hint: '吵鬧的', mode: 'spell' },
    { word: 'no-one', emoji: 'Ⓝ', hint: '沒有人', mode: 'grammar', sentence: '___ answered the phone.', options: ['No-one', 'Anyone', 'Someone', 'Everyone'], correct: 'no-one', translation: '沒有人接電話。' },
    { word: 'north', emoji: 'Ⓝ', hint: '北', mode: 'grammar', sentence: 'Canada is ___ of the USA.', options: ['north', 'south', 'east', 'west'], correct: 'north', translation: '加拿大在美國的北方。' },
    { word: 'November', emoji: 'Ⓝ', hint: '十一月', mode: 'spell' },
    { word: 'nowhere', emoji: 'Ⓝ', hint: '無處可去', mode: 'spell' },
    { word: 'ocean', emoji: '🌊', hint: '海洋', mode: 'match' },
    { word: 'October', emoji: 'Ⓞ', hint: '十月', mode: 'spell' },
    { word: 'octopus', emoji: '🐙', hint: '章魚', mode: 'listening' },
    { word: 'of course', emoji: 'Ⓞ', hint: '當然', mode: 'spell' },
    { word: 'office', emoji: '🏢', hint: '辦公室', mode: 'match' },
    { word: 'olives', emoji: '🫒', hint: '橄欖', mode: 'match' },
    { word: 'once', emoji: 'Ⓞ', hint: '一次', mode: 'spell' },
    { word: 'online', emoji: 'Ⓞ', hint: '網路', mode: 'spell' },
    { word: 'other', emoji: 'Ⓞ', hint: '其他', mode: 'grammar', sentence: 'I want the ___ book, not this one.', options: ['other', 'another', 'others', 'each'], correct: 'other', translation: '我要另一本書，不是這本。' },
    { word: 'oven', emoji: 'ⓞ', hint: '烤箱', mode: 'spell' },
    { word: 'over', emoji: '🤭', hint: '結束', mode: 'grammar', sentence: 'The plane flew ___ the mountain.', options: ['over', 'under', 'through', 'along'], correct: 'over', translation: '飛機飛過了那座山。' },
    { word: 'p.m.', emoji: 'Ⓟ', hint: '下午（時間）', mode: 'spell' },
    { word: 'passenger', emoji: '🛳️', hint: '乘客', mode: 'match' },
    { word: 'past', emoji: 'Ⓟ', hint: '過去', mode: 'grammar', sentence: 'It is ten minutes ___ five.', options: ['past', 'to', 'for', 'since'], correct: 'past', translation: '現在是五點過十分。' },
    { word: 'path', emoji: 'Ⓟ', hint: '路徑', mode: 'spell' },
    { word: 'pepper', emoji: '🌶️', hint: '胡椒', mode: 'match' },
    { word: 'perhaps', emoji: 'Ⓟ', hint: '也許', mode: 'spell' },
    { word: 'photographer', emoji: 'Ⓟ', hint: '攝影師', mode: 'spell' },
    { word: 'piece', emoji: '🧩', hint: '一塊', mode: 'match' },
    { word: 'pilot', emoji: '🧑‍✈️', hint: '飛行員', mode: 'match' },
    { word: 'pizza', emoji: '🍕', hint: '披薩', mode: 'match' },
    { word: 'planet', emoji: '🪐', hint: '行星', mode: 'match' },
    { word: 'plastic', emoji: 'Ⓟ', hint: '塑膠', mode: 'spell' },
    { word: 'platform', emoji: 'Ⓟ', hint: '平台', mode: 'spell' },
    { word: 'pleased', emoji: '😄', hint: '高興', mode: 'match' },
    { word: 'pocket', emoji: 'Ⓟ', hint: '口袋', mode: 'spell' },
    { word: 'police officer', emoji: '👮', hint: '警察', mode: 'match' },
    { word: 'police station', emoji: 'Ⓟ', hint: '警察局', mode: 'spell' },
    { word: 'pond', emoji: 'Ⓟ', hint: '池塘', mode: 'spell' },
    { word: 'poor', emoji: 'Ⓟ', hint: '窮', mode: 'spell' },
    { word: 'pop music', emoji: 'Ⓟ', hint: '流行音樂', mode: 'spell' },
    { word: 'popular', emoji: 'Ⓟ', hint: '流行的', mode: 'spell' },
    { word: 'post', emoji: '🏣', hint: '貼文', mode: 'match' },
    { word: 'post office', emoji: '🏣', hint: '郵局', mode: 'match' },
    { word: 'postcard', emoji: 'Ⓟ', hint: '明信片', mode: 'spell' },
    { word: 'prefer', emoji: 'Ⓟ', hint: '更喜歡', mode: 'spell' },
    { word: 'prize', emoji: 'Ⓟ', hint: '獎品', mode: 'spell' },
    { word: 'problem', emoji: 'Ⓟ', hint: '問題', mode: 'spell' },
    { word: 'programme', emoji: 'Ⓟ', hint: '節目', mode: 'spell' },
    { word: 'project', emoji: 'Ⓟ', hint: '專案', mode: 'spell' },
    { word: 'pull', emoji: 'Ⓟ', hint: '拉', mode: 'spell' },
    { word: 'push', emoji: 'Ⓟ', hint: '推', mode: 'spell' },
    { word: 'puzzle', emoji: 'Ⓟ', hint: '拼圖', mode: 'spell' },
    { word: 'pyjamas', emoji: 'Ⓟ', hint: '睡衣', mode: 'spell' },
    { word: 'pyramid', emoji: 'Ⓟ', hint: '金字塔', mode: 'spell' },
    { word: 'quarter', emoji: '🌓', hint: '季度', mode: 'match' },
    { word: 'queen', emoji: '👑', hint: '女王', mode: 'match' },
    { word: 'quiz', emoji: 'Ⓠ', hint: '測驗', mode: 'spell' },
    { word: 'race', emoji: 'Ⓡ', hint: '種族', mode: 'spell' },
    { word: 'racing car', emoji: '🏎️', hint: '賽車', mode: 'match' },
    { word: 'railway', emoji: '🚃', hint: '鐵路', mode: 'listening' },
    { word: 'ready', emoji: 'Ⓡ', hint: '準備好了', mode: 'spell' },
    { word: 'remember', emoji: 'Ⓡ', hint: '記住', mode: 'spell' },
    { word: 'repair', emoji: 'Ⓡ', hint: '修理', mode: 'spell' },
    { word: 'repeat', emoji: '🔁', hint: '重複', mode: 'listening' },
    { word: 'restaurant', emoji: '🍽', hint: '餐廳', mode: 'listening' },
    { word: 'rich', emoji: '🤑', hint: '富有', mode: 'match' },
    { word: 'right', emoji: '🗯️', hint: '右（方向）', mode: 'grammar', sentence: 'Turn ___ at the traffic lights.', options: ['right', 'left', 'straight', 'forward'], correct: 'right', translation: '在紅綠燈處右轉。' },
    { word: 'ring', emoji: '💍', hint: '戒指', mode: 'match' },
    { word: 'rock music', emoji: 'Ⓡ', hint: '搖滾音樂', mode: 'spell' },
    { word: 'rocket', emoji: '🚀', hint: '火箭', mode: 'match' },
    { word: 'rucksack', emoji: '🎒', hint: '背包', mode: 'listening' },
    { word: 'salt', emoji: '🧂', hint: '鹽', mode: 'match' },
    { word: 'same', emoji: 'Ⓢ', hint: '一樣', mode: 'spell' },
    { word: 'save', emoji: '💾', hint: '儲存', mode: 'listening' },
    { word: 'science', emoji: '🔬', hint: '科學', mode: 'match' },
    { word: 'scissors', emoji: '✂️', hint: '剪刀', mode: 'listening' },
    { word: 'screen', emoji: '💻', hint: '螢幕', mode: 'match' },
    { word: 'search', emoji: '🔍', hint: '搜尋', mode: 'match' },
    { word: 'secret', emoji: '㊙️', hint: '秘密', mode: 'match' },
    { word: 'sell', emoji: '💰', hint: '賣', mode: 'match' },
    { word: 'September', emoji: 'Ⓢ', hint: '九月', mode: 'spell' },
    { word: 'seven hundred', emoji: 'Ⓢ', hint: '七百', mode: 'spell' },
    { word: 'several', emoji: 'Ⓢ', hint: '幾個', mode: 'spell' },
    { word: 'shampoo', emoji: '🧼', hint: '洗髮精', mode: 'listening' },
    { word: 'shelf', emoji: 'Ⓢ', hint: '架子', mode: 'spell' },
    { word: 'should', emoji: 'Ⓢ', hint: '應該', mode: 'spell' },
    { word: 'silver', emoji: '🥈', hint: '銀', mode: 'listening' },
    { word: 'since', emoji: 'Ⓢ', hint: '自從', mode: 'grammar', sentence: 'I have been here ___ ten o\'clock.', options: ['since', 'for', 'during', 'in'], correct: 'since', translation: '我自從十點起就在這裡了。' },
    { word: 'singer', emoji: '🧑‍🎤', hint: '歌手', mode: 'match' },
    { word: 'six hundred', emoji: 'Ⓢ', hint: '六百', mode: 'spell' },
    { word: 'ski', emoji: '🎿', hint: '滑雪', mode: 'listening' },
    { word: 'skyscraper', emoji: '🏢', hint: '摩天大樓', mode: 'listening' },
    { word: 'sledge', emoji: '🛷', hint: '雪橇', mode: 'match' },
    { word: 'smell', emoji: '👃', hint: '氣味', mode: 'listening' },
    { word: 'snack', emoji: 'Ⓢ', hint: '小吃', mode: 'spell' },
    { word: 'snowball', emoji: 'Ⓢ', hint: '滾雪球', mode: 'spell' },
    { word: 'snowboard', emoji: 'Ⓢ', hint: '滑雪板', mode: 'spell' },
    { word: 'snowboarding', emoji: 'Ⓢ', hint: '單板滑雪', mode: 'spell' },
    { word: 'snowman', emoji: '⛄', hint: '雪人', mode: 'listening' },
    { word: 'so', emoji: 'Ⓢ', hint: '所以', mode: 'grammar', sentence: 'It was raining, ___ I stayed home.', options: ['so', 'because', 'but', 'although'], correct: 'so', translation: '下雨了，所以我待在家裡。' },
    { word: 'soap', emoji: '🧼', hint: '肥皂', mode: 'listening' },
    { word: 'soft', emoji: 'Ⓢ', hint: '軟的', mode: 'spell' },
    { word: 'somewhere', emoji: 'Ⓢ', hint: '某處', mode: 'spell' },
    { word: 'soon', emoji: '🔜', hint: '很快', mode: 'listening' },
    { word: 'sore', emoji: 'Ⓢ', hint: '酸痛', mode: 'spell' },
    { word: 'sound', emoji: 'Ⓢ', hint: '聲音', mode: 'spell' },
    { word: 'south', emoji: 'Ⓢ', hint: '南', mode: 'grammar', sentence: 'Australia is in the ___.', options: ['south', 'north', 'east', 'west'], correct: 'south', translation: '澳洲在南方。' },
    { word: 'space', emoji: '👨‍🚀', hint: '空間', mode: 'match' },
    { word: 'spaceship', emoji: '🚀', hint: '太空船', mode: 'match' },
    { word: 'speak', emoji: '🙊', hint: '說話', mode: 'match' },
    { word: 'special', emoji: 'Ⓢ', hint: '特別的', mode: 'spell' },
    { word: 'spend', emoji: 'Ⓢ', hint: '花費', mode: 'spell' },
    { word: 'spoon', emoji: '🥄', hint: '湯匙', mode: 'listening' },
    { word: 'spot', emoji: 'Ⓢ', hint: '現貨', mode: 'spell' },
    { word: 'spotted', emoji: 'Ⓢ', hint: '發現的', mode: 'spell' },
    { word: 'spring', emoji: '🌸', hint: '春天', mode: 'listening' },
    { word: 'stadium', emoji: '🏟️', hint: '體育場', mode: 'listening' },
    { word: 'stage', emoji: 'Ⓢ', hint: '舞台（劇院）', mode: 'spell' },
    { word: 'stamp', emoji: 'Ⓢ', hint: '郵票', mode: 'spell' },
    { word: 'stay', emoji: 'Ⓢ', hint: '留下來', mode: 'spell' },
    { word: 'step', emoji: 'Ⓢ', hint: '步驟', mode: 'spell' },
    { word: 'still', emoji: 'Ⓢ', hint: '仍然', mode: 'spell' },
    { word: 'stone', emoji: '🗿', hint: '石頭', mode: 'listening' },
    { word: 'storm', emoji: 'Ⓢ', hint: '風暴', mode: 'spell' },
    { word: 'straight on', emoji: 'Ⓢ', hint: '直接', mode: 'grammar', sentence: 'Go ___ and you will see the shop.', options: ['straight on', 'left', 'right', 'back'], correct: 'straight on', translation: '一直往前走，你就會看到那家店。' },
    { word: 'strange', emoji: 'Ⓢ', hint: '奇怪的', mode: 'spell' },
    { word: 'strawberry', emoji: '🍓', hint: '草莓', mode: 'listening' },
    { word: 'stream', emoji: 'Ⓢ', hint: '流', mode: 'spell' },
    { word: 'stripe', emoji: 'Ⓢ', hint: '條紋', mode: 'spell' },
    { word: 'striped', emoji: 'Ⓢ', hint: '條紋的', mode: 'spell' },
    { word: 'student', emoji: '🧑‍🎓', hint: '學生', mode: 'listening' },
    { word: 'study', emoji: 'Ⓢ', hint: '學習', mode: 'spell' },
    { word: 'subject', emoji: 'Ⓢ', hint: '主題', mode: 'spell' },
    { word: 'such', emoji: 'Ⓢ', hint: '這樣的', mode: 'grammar', sentence: 'It was ___ a nice day that we went out.', options: ['such', 'so', 'too', 'very'], correct: 'such', translation: '那是如此好的一天以致於我們出去了。' },
    { word: 'suddenly', emoji: 'Ⓢ', hint: '突然', mode: 'spell' },
    { word: 'sugar', emoji: 'Ⓢ', hint: '糖', mode: 'spell' },
    { word: 'suitcase', emoji: '🧳', hint: '行李箱', mode: 'listening' },
    { word: 'summer', emoji: '🍹', hint: '夏天', mode: 'listening' },
    { word: 'sunglasses', emoji: '🕶', hint: '墨鏡', mode: 'match' },
    { word: 'sure', emoji: 'Ⓢ', hint: '當然', mode: 'spell' },
    { word: 'surname', emoji: 'Ⓢ', hint: '姓氏', mode: 'spell' },
    { word: 'surprise', emoji: '😮', hint: '驚喜', mode: 'listening' },
    { word: 'swan', emoji: '🦢', hint: '天鵝', mode: 'listening' },
    { word: 'swing', emoji: 'Ⓢ', hint: '鞦韆', mode: 'spell' },
    { word: 'take', emoji: 'Ⓣ', hint: '花費（時間）', mode: 'spell' },
    { word: 'taste', emoji: '👅', hint: '味道', mode: 'listening' },
    { word: 'taxi', emoji: '🚕', hint: '計程車', mode: 'match' },
    { word: 'team', emoji: 'Ⓣ', hint: '團隊', mode: 'spell' },
    { word: 'telephone', emoji: '☎️', hint: '電話', mode: 'match' },
    { word: 'tent', emoji: '⛺', hint: '帳篷', mode: 'listening' },
    { word: 'thank', emoji: 'Ⓣ', hint: '謝謝', mode: 'spell' },
    { word: 'theatre', emoji: 'Ⓣ', hint: '劇院', mode: 'spell' },
    { word: 'thousand', emoji: 'Ⓣ', hint: '千', mode: 'spell' },
    { word: 'three hundred', emoji: 'Ⓣ', hint: '三百', mode: 'spell' },
    { word: 'through', emoji: 'Ⓣ', hint: '透過', mode: 'grammar', sentence: 'The train went ___ the tunnel.', options: ['through', 'across', 'along', 'into'], correct: 'through', translation: '火車穿過了隧道。' },
    { word: 'tidy', emoji: 'Ⓣ', hint: '整潔', mode: 'spell' },
    { word: 'time', emoji: 'Ⓣ', hint: '時間', mode: 'spell' },
    { word: 'timetable', emoji: 'Ⓣ', hint: '時間表', mode: 'spell' },
    { word: 'toe', emoji: 'Ⓣ', hint: '腳趾', mode: 'spell' },
    { word: 'tomorrow', emoji: 'Ⓣ', hint: '明天', mode: 'spell' },
    { word: 'tonight', emoji: 'Ⓣ', hint: '今晚', mode: 'spell' },
    { word: 'torch', emoji: '🔦', hint: '火炬', mode: 'match' },
    { word: 'tortoise', emoji: '🐢', hint: '烏龜', mode: 'listening' },
    { word: 'tour', emoji: 'Ⓣ', hint: '遊覽', mode: 'spell' },
    { word: 'trainers', emoji: '👟', hint: '培訓師', mode: 'match' },
    { word: 'tune', emoji: 'Ⓣ', hint: '調', mode: 'spell' },
    { word: 'turn', emoji: 'Ⓣ', hint: '轉', mode: 'spell' },
    { word: 'turn off', emoji: 'Ⓣ', hint: '關掉', mode: 'spell' },
    { word: 'turn on', emoji: 'Ⓣ', hint: '打開', mode: 'spell' },
    { word: 'twice', emoji: 'Ⓣ', hint: '兩次', mode: 'spell' },
    { word: 'two hundred', emoji: 'Ⓣ', hint: '兩百', mode: 'spell' },
    { word: 'tyre', emoji: 'Ⓣ', hint: '輪胎', mode: 'spell' },
    { word: 'umbrella', emoji: '☔', hint: '雨傘', mode: 'match' },
    { word: 'unfriendly', emoji: 'Ⓤ', hint: '不友善的', mode: 'spell' },
    { word: 'unhappy', emoji: 'Ⓤ', hint: '不高興', mode: 'spell' },
    { word: 'university', emoji: 'Ⓤ', hint: '大學', mode: 'spell' },
    { word: 'unkind', emoji: 'Ⓤ', hint: '不友善的', mode: 'spell' },
    { word: 'untidy', emoji: 'Ⓤ', hint: '不整潔', mode: 'spell' },
    { word: 'until', emoji: 'Ⓤ', hint: '直到', mode: 'grammar', sentence: 'Wait here ___ I return.', options: ['until', 'since', 'for', 'during'], correct: 'until', translation: '在這裡等直到我回來。' },
    { word: 'unusual', emoji: 'Ⓤ', hint: '不尋常的', mode: 'spell' },
    { word: 'use', emoji: 'Ⓤ', hint: '使用', mode: 'spell' },
    { word: 'usually', emoji: 'Ⓤ', hint: '通常', mode: 'spell' },
    { word: 'view', emoji: 'Ⓥ', hint: '查看', mode: 'spell' },
    { word: 'violin', emoji: '🎻', hint: '小提琴', mode: 'listening' },
    { word: 'visit', emoji: 'Ⓥ', hint: '訪問', mode: 'spell' },
    { word: 'volleyball', emoji: '🏐', hint: '排球', mode: 'match' },
    { word: 'waiter', emoji: 'Ⓦ', hint: '服務生', mode: 'spell' },
    { word: 'warm', emoji: 'Ⓦ', hint: '溫暖', mode: 'spell' },
    { word: 'way', emoji: 'Ⓦ', hint: '方式', mode: 'spell' },
    { word: 'west', emoji: 'Ⓦ', hint: '西', mode: 'grammar', sentence: 'The sun sets in the ___.', options: ['west', 'east', 'north', 'south'], correct: 'west', translation: '太陽從西方落下。' },
    { word: 'wheel', emoji: '🛞', hint: '輪子', mode: 'listening' },
    { word: 'while', emoji: 'Ⓦ', hint: '同時', mode: 'grammar', sentence: 'I fell asleep ___ I was reading.', options: ['while', 'during', 'since', 'before'], correct: 'while', translation: '我在讀書的時候睡著了。' },
    { word: 'whisper', emoji: '🤫', hint: '耳語', mode: 'match' },
    { word: 'whistle', emoji: '🎶', hint: '口哨', mode: 'match' },
    { word: 'wife', emoji: 'Ⓦ', hint: '妻子', mode: 'spell' },
    { word: 'wifi', emoji: '📶', hint: '無線網路', mode: 'listening' },
    { word: 'wild', emoji: 'Ⓦ', hint: '野生的', mode: 'spell' },
    { word: 'will', emoji: 'Ⓦ', hint: '會', mode: 'spell' },
    { word: 'win', emoji: '🏆', hint: '贏', mode: 'match' },
    { word: 'wing', emoji: '🪽', hint: '翼', mode: 'listening' },
    { word: 'winner', emoji: 'Ⓦ', hint: '獲勝者', mode: 'spell' },
    { word: 'winter', emoji: '❄️', hint: '冬天', mode: 'listening' },
    { word: 'without', emoji: '😶', hint: '沒有', mode: 'grammar', sentence: 'He left the house ___ his coat.', options: ['without', 'with', 'by', 'for'], correct: 'without', translation: '他沒穿外套就離開了家。' },
    { word: 'wonderful', emoji: 'Ⓦ', hint: '太棒了', mode: 'grammar', sentence: 'What a ___ day it is today!', options: ['wonderful', 'bad', 'terrible', 'sore'], correct: 'wonderful', translation: '今天真是美好的一天！' },
    { word: 'wood', emoji: '🪵', hint: '木頭', mode: 'listening' },
    { word: 'wool', emoji: 'Ⓦ', hint: '羊毛', mode: 'spell' },
    { word: 'worried', emoji: '😟', hint: '擔心', mode: 'match' },
    { word: 'x-ray', emoji: '🩻', hint: 'X射線', mode: 'listening' },
    { word: 'yet', emoji: 'Ⓨ', hint: '還', mode: 'spell' },
    { word: 'yoghurt', emoji: 'Ⓨ', hint: '優格', mode: 'spell' },
    { word: 'zero', emoji: '0️⃣', hint: '零', mode: 'match' },
    { word: 'eighteen', emoji: 'Ⓔ', hint: '十八', mode: 'spell' },
    { word: 'spell', emoji: 'Ⓢ', hint: '咒語', mode: 'spell' },
    { word: 'story', emoji: 'Ⓢ', hint: '故事', mode: 'spell' }
  ]
};
